### ISSUE TITLE
Minor glitches and additions for the app

### ISSUE THREAD

**Issue by SilkInFlames** [Dar9586/NClientV2#100]
So I've been testing the app and here's what I found while I was making my best finding ways to break it (hope it's not all stuff that could be fixed by just a button I didn't notice while testing it lol)

This is just focused on the little things, they're not really important alone, but together they would make for an overall better experience, anyways here's the list:

-The app crashes after you change the language or theme and exit the settings menu.

-While you are in the settings menu, everytime you minimize and open the app, all the text duplicates below the original thing.

-When you enter the first page in the page viewer, the number on it displays 999/999 instead of 1/*insert number* (it returns to normal if you scroll to the next page and then to the first one, but it will happen again if you exit the page viewer and enter in the first one again).

-When going through the page viewer, one page will eventually have an error loading and the only way to reload it is to either exit the page viewer and re-enter it or to scroll 2 or 3 pages after that image and go back so it reloads. An error message saying "An error happened while loading the image" along with a "Try again" button would be much appreciated.

-When you use the "Download all galleries in this page", while one gallery downloads normally, all the other ones shows as 100% done downloading while that is not actually true, to get around this, all other galleries waiting for download should display as "Waiting in queue"

-As a really tiny design thing, it would be great if the inferior text on the confirmation boxes (OK, CANCEL, etc) were white in the dark theme and black in the light one because it's normally kinda hard to read it.

-Also please add the option to directly input a number in the page viewer, just like with the app's main page, it would be much better than to scroll using the bar when the gallery is 50+ pages long.

Thank you for putting so much work on the app, it's already much better than the actual site interface, just know that I'm really thankful for it!

**Comment by Dar9586** [comment]
Thanks for all the suggestions, I will fix them soon. The only one I couldn't replicate is the first neither in Android JellyBean (API 16) neither in Android Pie (API 28), the behaviour should be of restarting the app, if this doesn't happen I'd like to know your Android version to be able to replicate it

**Comment by SilkInFlames** [comment]
I use the Android 5.1.1 lollipop version

**Comment by SilkInFlames** [comment]
Also, I just noticed that the "Sort by popular" button doesn't work in the main page, I think that could be worked around by using a search result like "-qoiahsbxnxnzkqpqojska" or some text that would never become a gallery as the main page, because in the site it enables you to navigate through popular without actually adding any search terms

**Comment by Dar9586** [comment]
They should all be fixed in 2.2.1
- If you click on the page number it will now open the page chooser
- Now the image shown when the download failed can be clicked and it will retry downloading that page
- The download not started won't have a percentage and an indeterminate progress bar
- Now the texts should all be visible

**Comment by SilkInFlames** [comment]
Wow you work really fast damn lol, like thank you really much

**Comment by SilkInFlames** [comment]
UPDATE: About the reload function, I found two bugs with the reader:

1- When going through a gallery normally with every image loading, when one of the pages has to be reloaded, it will load for a while and will fail again, this happens with the page you reloaded and all the ones that come after it, it only fixes itself by exiting the reader and opening it again.

2- The app tends to crash a lot while going through the reader, normally when you're browsing through lot of unloaded pages

**Comment by Dar9586** [comment]
Now it should be fixed

**Comment by TusharGod** [comment]
There should be a section for downloaded Chapter
But i see no option like that
All chapter downloaded just Vanishes from the app and cannot be Obtained thru App

Can i have a Hint of where do the downloaded files go?
