### ISSUE TITLE
Downloads appear empty

### ISSUE THREAD

**Issue by Pookie06** [Dar9586/NClientV2#103]
I have several galeries downloaded. I can see the images through a file manager but when i try to see them through the app it shows no downloaded galeries.

**Comment by Dar9586** [comment]
Could you tell me your Android version?
Check if in your folders there is a file called .nomedia, it should be hidden by default, if you open it it should contain a number

**Comment by Pookie06** [comment]
Android version 9
Software version Q720CS10N

I am unable to see any of the downloaded galleries. I can see when they are downloading but once they finish they are no longer listed

**Comment by Pookie06** [comment]
I downgraded to 2.2.0 and confirmed it functions in that version. Once i updated it broke again. FYI
