### ISSUE TITLE
Not a bug report but feature request

### ISSUE THREAD

**Issue by aryanDramtel** [Dar9586/NClientV2#105]
Hello Dev,
Sorry for posting this here as i don't know where to post feature request (or if there is any place like that). I just wanted to let you know that it would be great if you could add a feature where you can watch the 5or6 digit number on urls of the given manga, and a section to input that number to find its manga. Because people on groups and on public share that 5-6 digit numbers more often.

**Comment by SilkInFlames** [comment]
You can already do both. When you enter a gallery, just press the three dots thing and press "share", then you can just copy the url and isolate the numbers later, as for searching by numbers, you can just input them directly into the search box and you will be redirected to the searched gallery page. Hope I explained this well, the number search thing is kinda obscure though so it's not a big deal if you missed it.

**Comment by aryanDramtel** [comment]
Wow thanks a lot, I forgot that the share option would provide link which is literally the website address and the numbers itself.
