### ISSUE TITLE
Downloading Problems

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#108]
~Random manga feature isnt working. Probably it still uses the nhentai.net API, you may hide it when "Use nhent.ai" is turned on or if nhent.ai supports, you may use its API too.~
**Fixed**

**Comment by Dar9586** [comment]
It seems that nhent.ai doesn't support random manga, but I can simulate it.
It will be added in the next update, if there are other not working part make me know

**Comment by hmaltr** [comment]
Well I couldnt find anything that looks suspicious/broken right now but may i recommend having an discord server for communicating easier? I will hunt for bugs tommorrow  ;)

**Comment by hmaltr** [comment]
@Dar9586 It looks like also the download feature doesnt work with nhent.ai probably still uses nhentai.net API. Well you may try downloading by loading the page and downloading the photo. 

Also there is an problem with normal downloading that causes the image to load partially or doesnt download at all but the others are OK.
