### ISSUE TITLE
Issue searching using an hentai's related tag

### ISSUE THREAD

**Issue by teo3300** [Dar9586/NClientV2#11]
Found a problem using hentai-related tags for search

- open a random hentai and select one of the related tags (a_tag) for search
- return to the main page (the one with NClientV2 on the top left) using the back button or rebooting the app
- refreshing the main page only hentai with (a_tag) are visible, no tag can be edited or removed, opening the page in the browser the search bar contains (tag: "a_tag")

**Comment by Dar9586** [comment]
Thanks for the reporting. I will fix it on the next update

**Comment by Dar9586** [comment]
Fixed in 1.8.5
