### ISSUE TITLE
Impossible to know if a book is saved in the online library

### ISSUE THREAD

**Issue by teo3300** [Dar9586/NClientV2#116]
The option "Remove from online favorites" appears as "Add to online favorites" in the "Offline favorites", the button works, so it's possible to add and remove books from the online library, but the text on it never changes, it's not possible to know if a book is saved or not

**Comment by Dar9586** [comment]
In 2.2.8 I opted to simply replace the initial label of the setting, since these favorites data are stored locally it seemed like a waste make other requests only to know if it is favorite. Even because if there are too many request in a short amount of time the site could temp-ban your device.
