### ISSUE TITLE
(Bug) Non English Characters

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#117]
When searching with **ö, ç, ğ, ü ş, İ** the website gives an error
![image](https://user-images.githubusercontent.com/43448461/81497165-735e6480-92c5-11ea-95f3-3464571166c4.png)  or an 502 error 
![image](https://user-images.githubusercontent.com/43448461/81497200-9ee14f00-92c5-11ea-81c4-b1ec3408c401.png) disallowing these characters and notifying the user when an error happens could be helpful.

**Comment by Dar9586** [comment]
This isn't a screen from the app but from the site. In the app they work as intended, these galleries doesn't exist, so it will show nothing
