### ISSUE TITLE
Favorites place? 

### ISSUE THREAD

**Issue by dolicon** [Dar9586/NClientV2#12]
Hi.  Thanks for this fantastic app. 

Can you please tell me where does your app store the numbers of favorite manga? 

I want to add my favorite folder from the official app but i don't know where to put it.

**Comment by Dar9586** [comment]
They are stored in internal_sdcard/NClientV2/GALLERYNAME

**Comment by dolicon** [comment]
Thanks for your reply. 
But i noticed that the galleries stored are the downloaded manga only,not the favorites.
I found there 3 folders only while i liked more than 30 manga. 
The favorites must be stored else where because  i cleared cache and disconnected from wifi but my favourites still show up.

**Comment by Dar9586** [comment]
The favorites are stored into a Database saved into a private folder with the settings of the app
