### ISSUE TITLE
[Feature Request] Add download location options

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#124]
Adding an user selected downloading location/directory could be helpful instead of turning on some developer options or moving them to the desired location manually (This issue is based off #73 )

**Comment by hmaltr** [comment]
@Dar9586 are you thinking of adding a such option?

**Comment by Dar9586** [comment]
I'd like to implement it, but I haven't a device with external SD card and the emulator doesn't support that feature.
Another problem is the lack of proper documentation on how to implement it, since between the SDK version the mode used to write to an external SD card has changed and they are incompatible between them (I should implement every the write to storage in at least 3 different ways without the possibility to test them properly hoping they work). Since I can't test them properly I preferred to delay the addition of this feature until I find a reliable test environment.

**Comment by hmaltr** [comment]
@Dar9586 you can send me a test version if you want i got android 10 and 7 running devices i can test for you.

**Comment by Dar9586** [comment]
I tried my best to implement it in this debug version.
For version before kitkat the sdcard should be accessible normally, so using the directory picker or copying the folder path from a file manager
For version after lollipop there is a (slow) API which is used to access the external code (this is the only method).
For KitKat I couldn't figure how to implement it
[app-debug.zip](https://github.com/Dar9586/NClientV2/files/4807710/app-debug.zip)

**Comment by hmaltr** [comment]
> I tried my best to implement it in this debug version.
> For version before kitkat the sdcard should be accessible normally, so using the directory picker or copying the folder path from a file manager
> For version after lollipop there is a (slow) API which is used to access the external code (this is the only method).
> For KitKat I couldn't figure how to implement it
> [app-debug.zip](https://github.com/Dar9586/NClientV2/files/4807710/app-debug.zip)
> 

Well it worked at least but it had **devastating** effects like:
*Manga thumbs being broken.*
*The other directory (if local sd card, if sd card local) is not accessible*
**It would be better if you also added an default location for SD and local directories like android/data/com.dar9586.nclientv2 etc.**
@Dar9586

**Comment by hmaltr** [comment]
Also auto-updater for that debug version is totally broken.

**Comment by Dar9586** [comment]
Now it should work. And is only using the old method to access the app, which is faster but limits the selectable location. This should work fine from API 19 (KitKat) [app-debug.zip](https://github.com/Dar9586/NClientV2/files/4814857/app-debug.zip)

**Comment by hmaltr** [comment]
@Dar9586 Sadly I cant even install it, can you check the integrity?

**Comment by Dar9586** [comment]
For that version Android Studio didn't bring any problem, maybe it's a version incompability. This has a different version code and has no reported error:
[NClientV2 2.4.5 Debug.zip](https://github.com/Dar9586/NClientV2/files/4817700/NClientV2.2.4.5.Debug.zip)

**Comment by hmaltr** [comment]
@Dar9586 Seems to work! though I cant test downloading since ***nhent.ai is down***. Also I recommend to read both SD and local device folder and mix them. Since when you select SD the mangas downloaded to local storage **disappears**.

**Comment by Dar9586** [comment]
Now the folder can be selected from the Downloaded manga toolbar, so you can manage them independently
