### ISSUE TITLE
更新到3.0后縮略圖全部無法顯示

### ISSUE THREAD

**Issue by WeiRi** [Dar9586/NClientV2#125]
如題所述，更新前一切正常，更新后在線流覽，查看已下載，點進某一漫畫查看縮略圖，這三個地方的圖片都不能正常顯示，但是其他地方並無異常，能正常下載

**Comment by Dar9586** [comment]
I don't know if Google translate worked well, but maybe you should check the data usage settings.
If it's not that, please send the details in English because I don't understand Chinese

**Comment by WeiRi** [comment]
> I don't know if Google translate worked well, but maybe you should check the data usage settings.
> If it's not that, please send the details in English because I don't understand Chinese

OK，the problem is that all thumbnails don't show in the application on version 3.0. The application worked normally before this update, but after it ,every picture can't be shown in the app.However, downloaded picture are as usual outside the app.
I've check all the settings in the application,but it seems this can't solve the problem. If you are talking about the mobile phone setting , I ensure that there was no setting change during the updating.
These are my problems, maybe my description can help you solve bugs

**Comment by hmaltr** [comment]
> > I don't know if Google translate worked well, but maybe you should check the data usage settings.
> > If it's not that, please send the details in English because I don't understand Chinese
> 
> OK，the problem is that all thumbnails don't show in the application on version 2.3.0. The application worked normally before this update, but after it ,every picture can't be shown in the app.However, downloaded picture are as usual outside the app.
> I've check all the settings in the application,but it seems this can't solve the problem. If you are talking about the mobile phone setting , I ensure that there was no setting change during the updating.
> These are my problems, I hope my description can help you solve bugs

Have you checked the app permissions? Maybe you or your system accidentally disabled some of the permissions that the app needs. Or you might have checked "Do not ask again" ?

**Comment by WeiRi** [comment]
> > > I don't know if Google translate worked well, but maybe you should check the data usage settings.
> > > If it's not that, please send the details in English because I don't understand Chinese
> > 
> > 
> > OK，the problem is that all thumbnails don't show in the application on version 2.3.0. The application worked normally before this update, but after it ,every picture can't be shown in the app.However, downloaded picture are as usual outside the app.
> > I've check all the settings in the application,but it seems this can't solve the problem. If you are talking about the mobile phone setting , I ensure that there was no setting change during the updating.
> > These are my problems, I hope my description can help you solve bugs
> 
> Have you checked the app permissions? Maybe you or your system accidentally disabled some of the permissions that the app needs. Or you might have checked "Do not ask again" ?

I just checked the permission settings.This app only asks for usual permissions, and is permitted.It seems this is not the reason. 
Besides, my Android system is version 4.42, is this related to the problem?

**Comment by hmaltr** [comment]
Well this app support API 14< (Kitkat and above) then it shouldnt be the problem. Have you tried reinstalling the app or rebooting your device (I cant help any further sorry :( )

**Comment by WeiRi** [comment]
> Well this app support API 14< (Kitkat [4.4.x] and above) then it shouldnt be the problem. Have you tried reinstalling the app or rebooting your device (I cant help any further sorry :( )

I tried turn it back to v2.2.9, and reinstalling ,but these don't works.
Maybe this problem can be fixed after next update.Thanks for your kindness :)

**Comment by WeiRi** [comment]
In addtion, I tested the network during using the app. It seems that the problem is that the app doesn't request for pictures but just basic details from the server. However ,it's strange that allready-downloaded pictures can't be shown through the apps.

**Comment by hmaltr** [comment]
> In addtion, I tested the network during using the app. It seems that the problem is that the app doesn't request for pictures but just basic details from the server. However ,it's strange that allready-downloaded pictures can't be shown through the apps.

If thats the case did you try cleaning your cache and switching "Use nhent.ai" on/off?

**Comment by WeiRi** [comment]
> > In addtion, I tested the network during using the app. It seems that the problem is that the app doesn't request for pictures but just basic details from the server. However ,it's strange that allready-downloaded pictures can't be shown through the apps.
> 
> If thats the case did you try cleaning your cache and switching "Use nhent.ai" on/off?

thanks, I just solved it ,but not in this way.
I tried uninstall and return to v2.28,but come across the same problem, even this version used to be normal.
However, when I update it to v2.30, the problem just solved! what a stange thing. :)
maybe this has something to do with remained files or cache in the phone?
