### ISSUE TITLE
[Feature Request]- Handle long pages

### ISSUE THREAD

**Issue by imgregduh** [Dar9586/NClientV2#127]
It looks like the application will open the page and zoom to fit to the screen. When the pages are long you wouldn't want to see the entire page initially because it will spoil what you haven't read yet.  If possible we should probably have a max zoom to fit if the page is too long for the device you are using then you would just scroll down to see the rest of the page.

![Screenshot_20200521-150841](https://user-images.githubusercontent.com/5440162/82601475-3885e780-9b75-11ea-86ab-78fea2b4c518.png)

**Comment by Dar9586** [comment]
https://github.com/Dar9586/NClientV2/issues/85#issuecomment-608996421
