### ISSUE TITLE
using the tag from the account Bug！

### ISSUE THREAD

**Issue by Bouncysig18** [Dar9586/NClientV2#13]
if i choose try to using the tag from my account online，the homepage of the nhentai in app show nothing. but when i close this，manga shows in homepage again.

**Comment by Dar9586** [comment]
Try the new version 1.8.6

**Comment by Bouncysig18** [comment]
When i uesd the new version 1.8.6, 
1. i cannot use the search funtion
2. the main page cannot be refreshed. 
3.the nation flag(language? ) cannot work well to filter the other language which i hope to filter it
4. when i start the app. it always suggest me to update the app from 1.8.6 to 1.8.5(it seems normal?)
