### ISSUE TITLE
Auto zoom feature on tall images

### ISSUE THREAD

**Issue by domino8765** [Dar9586/NClientV2#130]
Hello, can you add a feature where it zooms into comics with single very tall images. Please see attached image.

Thanks 😊.
![Screenshot_20200523-181907_NClientV2](https://user-images.githubusercontent.com/65833633/82741658-8855e180-9d22-11ea-8f55-baf1f8d3ef58.jpg)

**Comment by domino8765** [comment]
I meant auto zoom, so I don't have to tap  the image multiple times to get it to fit my screen/phone display. The website does this, thanks

**Comment by Dar9586** [comment]
https://github.com/Dar9586/NClientV2/issues/85#issuecomment-608996421
Maybe this can help
