### ISSUE TITLE
[Feature Request] Change title language in the main page

### ISSUE THREAD

**Issue by bbbbbw** [Dar9586/NClientV2#131]
In settings, users could change the title type while titles in the main page are not displayed as the selected type. For example, I select Japanese as title type. But in the main page titles of all the work are still in English. Only by clicking into the detail page can I see the Japanese title of the selected work. This might not be very user-friendly and hopefully it could be fixed.

**Comment by xjamespan** [comment]
Agreed, I met the same problem with u.

**Comment by Dar9586** [comment]
Because the gallerties shown in  NHentai search page are 'partial', and it is only one title, when you open the gallery instead all data are loaded and you can see all the 3 titles

**Comment by xjamespan** [comment]
> Because the galleries shown in NHentai search page are 'partial', and they only have one title.
> When you open the gallery instead all data are loaded and you can see all the 3 titles.
> The app can't fetch them during search due to excessive request should make

all right. I understand.
