### ISSUE TITLE
Offline favorites no pages

### ISSUE THREAD

**Issue by CarbonSheild** [Dar9586/NClientV2#134]
As of version 2.3.1, all of my offline favorites are said to have 0 pages. this is only seen when accessing the doujin from the offline favorites menu, accessing the same doujin from the online favorites, view history, and the main page/home works normally.

A50 running on android 10

**Comment by Bouncysig18** [comment]
+1, i also find the problem that i can use the online tag to filter the doujin(i have logged in ). the local tag function works.

**Comment by Dar9586** [comment]
If I understand the problem there is an option in settings to disable the online tags
