### ISSUE TITLE
Auto zoom too much on long pages

### ISSUE THREAD

**Issue by domino8765** [Dar9586/NClientV2#135]
Hello and thank you very much for reading my feedback and implementing it so quickly. But the auto zoom, zooms too much into the pictures and I have to zoom out a little every page to make it fit into the screen.

Please see attached photo. First picture is the auto zoom and second picture is me manually adjusting the page to fit the screen.

I also had the idea maybe the long pages could stack on top of each other to read from top to bottom infinitely.

Thank you for your hard work.

![Screenshot_20200525-061820_NClientV2](https://user-images.githubusercontent.com/65833633/82804248-f1874300-9e4f-11ea-8abb-08c165935537.jpg)
![Screenshot_20200525-061830_NClientV2](https://user-images.githubusercontent.com/65833633/82804262-f5b36080-9e4f-11ea-817f-6621327f250b.jpg)

**Comment by Dar9586** [comment]
If you want the images be one on top of the other you can use the single column mode
https://github.com/Dar9586/NClientV2/issues/85
