### ISSUE TITLE
Multiple unwanted downloaded mangas

### ISSUE THREAD

**Issue by rezzcrouz** [Dar9586/NClientV2#138]
Hi! Since this one is a different case, I will issue the problem I forgot to mention here. On the current version (version 2.3.2), I encountered another problem (bug, to be precise). I accidentally tapped on 'Download all galleries in this page' and it downloaded like a dozen mangas. I cancelled it from downloading them and I had to cancel them one by one, that really took my time much. When I was about to download a desired manga, they (the mentioned unwanted mangas above) suddenly appeared in my download folder. But this time, they weren't downloaded. At all. Only folders without images in it. It keeps happening whenever I downloaded my favorite mangas and I have to delete them manually. That keeps happening every time. This is annoying.

Sorry for the long post🙏

**Comment by Dar9586** [comment]
Should be fixes in 2.3.3
