### ISSUE TITLE
All tag sections are just the applied tags section

### ISSUE THREAD

**Issue by CarbonSheild** [Dar9586/NClientV2#157]
![Screenshot_20200610-222255_NClientV2](https://user-images.githubusercontent.com/16976888/84338049-10344c00-ab69-11ea-9780-6443820b63b7.jpg)
![Screenshot_20200610-222244_NClientV2](https://user-images.githubusercontent.com/16976888/84338051-10cce280-ab69-11ea-9579-34497aed0cbe.jpg)
![Screenshot_20200610-222227_NClientV2](https://user-images.githubusercontent.com/16976888/84338052-10cce280-ab69-11ea-8ef4-48253fa82d4a.jpg)
Latest version as of date.

**Comment by Kinuseka** [comment]
I downgraded my client to 2.3.8 and fixes it. It seems to be a new bug from 2.3.9
