### ISSUE TITLE
app无法登录

### ISSUE THREAD

**Issue by TAjimu-veda** [Dar9586/NClientV2#164]
版本：NClientV2 2.4.2
问题：无法通过左下角登录，但是我在nhentai.net已经登录上了
（可能不会及时上GitHub回复，但问题解决了我会继续使用的）
祝好~

**Comment by TAjimu-veda** [comment]
Version: NClientV2 2.4.2
Question: I can't log in through the lower left corner, but I have logged in at nhentai.net
(May not go to GitHub in time, but I will continue to use it if the problem is solved)
good luck~

**Comment by Dar9586** [comment]
The login is still beta, so it can have some issues
