### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by kidman9520** [Dar9586/NClientV2#165]
As the update 2.4.2 bring back the log in feature for favourite, I'm facing other problem where i enter my username (or email) and password correctly, it show that my username or my password is incorrect.

Wierd i remember my my username and password clearly.

Hope this problem can be fix.
Thank you.
![Screenshot_2020-06-14-04-55-13-51_8dc4a708c34f1c510344fe919321c07b](https://user-images.githubusercontent.com/66886064/84578941-45a49800-adfc-11ea-9cb1-18ce9d942a0c.jpg)

**Comment by Dar9586** [comment]
The login screen is only a webview, so if you put the same data on the site the result will be the same. It is a site problem and, I can't fix it
