### ISSUE TITLE
[Addition] Add no internet alert

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#167]
When on the main page or the login webview following things happen:
[Login](https://cdn.discordapp.com/attachments/608725424092086280/721825861933989999/Screenshot_20200614-233759_NClientV2.jpg)

[Main Menu](https://cdn.discordapp.com/attachments/608725424092086280/721826813692739655/Screenshot_20200614-234151_NClientV2.jpg)
Adding an exclamation mark saying check your internet connection and try again will be better for the UX.

**Comment by hmaltr** [comment]
Login still has the same issue main page works flawlessly

**Comment by Dar9586** [comment]
Since the login is only in Beta and may change I preferred not to touch it for now.

**Comment by hmaltr** [comment]
> Since the login is only in Beta and may change I preferred not to touch it for now.

Then im gonna close this for now.
