### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by kaisen7887** [Dar9586/NClientV2#173]
Everything is fine on 2_2.2.7
But the performance goes so low at 2_.2.2.8 and above.
Especially during reading of pictures
Of downloaded and online doujins.
(It always crashes on my phone)
And returning to 2_2.2.7 will make me to unable to search using numbers or titles.
Can you please put an option for us to use the older,more stable option?

**Comment by hmaltr** [comment]
Did you try reinstalling? *just in case* Also as far as I know a slow **connection** may cause performance issues.

Also an older stable build is kinda unavailable now. *depends on @Dar9586* *since Nhentai done some breaking changes to their site recently so older versions cant even read online*

**Comment by Dar9586** [comment]
Which version of the app are you using?

**Comment by kaisen7887** [comment]
@Dar9586 your latest version 2.4.7
I updated it to 2.4.8 by uninstalling 2.4.7 and installing 2.4.8 but still has performance issues.
When it come to the pictures,offline or online.

**Comment by kaisen7887** [comment]
@hmaltr my connection is good and i tried it multiple times but it has that problem when it come to reading the pictures.even reading downloaded doujins using version  2.4.0 and above makes ncllientv2 crash

**Comment by hmaltr** [comment]
Do you have a lot of downloaded mangas? It could be the reason that I can think of.

**Comment by kaisen7887** [comment]
@hmaltr i have 3 downloaded mangas but still has weak performance.mostly crashes when the pages showing up.

**Comment by hmaltr** [comment]
@Dar9586 Maybe the function you disabled couple weeks ago??
@kaisen7887 What is your android version / phone model / if an sd card is present / download location

**Comment by kaisen7887** [comment]
@hmaltr what function?

**Comment by kaisen7887** [comment]
Hyundai Areo 
5.0.2

**Comment by hmaltr** [comment]
> @hmaltr what function?

He disabled an function in an older version that caused every metadata to be loaded whether it was viewed or not i suppose.

**Comment by kaisen7887** [comment]
![Screenshot_2020-06-28-04-44-37](https://user-images.githubusercontent.com/53758833/85931880-0de72700-b8b7-11ea-854a-bafd07e0f6de.png)
I see the metadata but im talking about performance on the pictures.

**Comment by hmaltr** [comment]
Sadly this is the end of my knowledge land.. Ask @Dar9586 about it. I think he will figure it out.

**Comment by kaisen7887** [comment]
I always try to minimize the showing of pages cuz when those pages show up,my phone gone super laggy and has a good chance to crash.thats when i use 2.4.0 and above.

**Comment by kaisen7887** [comment]
hmaltr appreciated your reply

**Comment by Dar9586** [comment]
Reverted to 2.3.9 loading mode.
The problem probably was caused by the new image loading behaviour I implemented in 2.4.0, but seems that it requires a lot more RAM of the old and I didn't notice that. Now I reverted to the old method, so it should work as before

**Comment by kaisen7887** [comment]
@Dar9586 thanks for hearing my call.After that i updated the client,thhe app is running smooth again like in the past.im going to close this issue now.Till next time. <3
