### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by danialol94** [Dar9586/NClientV2#174]
I've already updated to the latest version, however the app doesn't seem to load anything, i don't know if the problem is on my end or the server end

![Screenshot_2020-06-23-11-16-38-872_com dar nclientv2](https://user-images.githubusercontent.com/50165231/85357356-b0b04600-b543-11ea-8cc5-922d1d9a4a14.jpg)

**Comment by hmaltr** [comment]
@danialol94 can you access to the nhentai.net or nhent.ai in your browser?

**Comment by danialol94** [comment]
I got this error when trying to accesa nhent.ai

![Screenshot_2020-06-23-14-41-23-424_com opera browser](https://user-images.githubusercontent.com/50165231/85369575-e7945500-b55f-11ea-9776-8988b06043f4.jpg)

**Comment by hmaltr** [comment]
Try **nhentai.net** nhent.ai can be tricky sometimes. *Go to Settings and turn off "Use nhent.ai" option*

**Comment by hmaltr** [comment]
*Also its normal for the app to unable to load anything since the website is down*

**Comment by danialol94** [comment]
I initially thought it was server issue since I've been using VPN, anyway thank you bro

**Comment by hmaltr** [comment]
@danialol94 You can close this issue if you want. Im glad I could help ya!
