### ISSUE TITLE
[Feature request] Changing default zoom on pages in the page viewer (not gallery scrolling)

### ISSUE THREAD

**Issue by infinitephantasm** [Dar9586/NClientV2#175]
often times when scrolling through pages with the page viewer, i use landscape mode (although this issue also happens on portrait), and i'll have to doubletap the screen to get the zoom at a level where i can properly read things without having to keep the screen so close (and also generally just to make it more enjoyable to read). if it's possible, a feature to make it so you can set the zoom by default (e.g. in settings, with 100%/125%/150%/max/etc...) would be fantastic and would make for a lot less time spent tapping my screen and more time spent swiping it. although i don't know if it's just simply not possible due to the way the viewer is made

**Comment by Dar9586** [comment]
Added in 2.4.6
