### ISSUE TITLE
No entries found

### ISSUE THREAD

**Issue by kidman9520** [Dar9586/NClientV2#177]
I'm facing a problem wheee i enter the Nhentai app and show nothing hut a message no entries found i try to refresh it but still the same. I turn on the Nhent.ai but still the same result.

**Comment by hmaltr** [comment]
@kidman9520 Make sure you can access both [nhentai.net](http://nhentai.net) and [nhent.ai](https://nhent.ai) in your browser. If you cant that means you might need an VPN. **Also FYI nhent.ai is down and cant be accessed right now**
