### ISSUE TITLE
App not installing updates on one+ 6

### ISSUE THREAD

**Issue by DietMocha** [Dar9586/NClientV2#178]
Install unknown apps set to allow NclientV2. Prompt to update from 2.0.5 to 2.4.5, then it says installing then App did not install. Installed originally from F-droid cause I couldn't find an .apk on github pull

**Comment by hmaltr** [comment]
@DietMocha here is the latest version [download link.](https://github.com/Dar9586/NClientV2/releases/download/2.4.5/NClientV2.2.4.5.Release.apk)

**Comment by DietMocha** [comment]
Thanks, uninstalling the F-droid version and reinstalling from linked worked. Apparently, it's a common issue on Android that pops up occasionally with app updates.

**Comment by hmaltr** [comment]
Im glad I could help! Dont forget to close issues if your issue is resolved or you are done with it.

**Comment by Dar9586** [comment]
The F-Droid version can be updated only from the F-Droid app, the prompt shown in the app are the updates for the Github version.
In the next version probably I'll add a disclaimer
