### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by riyan2401** [Dar9586/NClientV2#18]
![Screenshot_20190729-052749](https://user-images.githubusercontent.com/49383178/62013784-c7c6a680-b1c1-11e9-8fd0-6b9f8b22714c.png)

I can't see anything in my phone, this happen in every version.

My phone: Asus Zenfone Max 2

**Comment by teo3300** [comment]
You probably left some filter tags, you can remove 'em from "manage tags"
