### ISSUE TITLE
Restricted Site

### ISSUE THREAD

**Issue by Moshe215** [Dar9586/NClientV2#180]
I have had this problem since yesterday "no entries found", in Nhent.ai because on Nhentai.net it works well, the problem is that my internet provider is restricted to this page, is there any alternative or something I can do to access the site?

**Comment by hmaltr** [comment]
As far as i know there isnt :( You will need to wair for nhent.ai to get fixed

**Comment by hmaltr** [comment]
Though you can still use a VPN to access till nhent.ai gets fixed.

**Comment by Dar9586** [comment]
There is nothing I can do about this from the app, as stated from @hmaltr a VPN is the only way
