### ISSUE TITLE
[Bug] Sorting while searching

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#182]
While searching downloaded mangas when you change the **sorting setting**, the search is invalidated and it looks like you never searched.

**Comment by hmaltr** [comment]
**Update**

Search now partially broken. It rarely works as expected, other times it doesnt find anything. Although it exists and i can see it without searching. @Dar9586

**Comment by hmaltr** [comment]
Also the same issue happens when you refresh the search results. Turns back to normal like you never searched.

**Comment by Dar9586** [comment]
[app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838491/app-debug.zip)
Could you try if this version works, because I can't find any problem and I changed the only thing which seemed different

**Comment by hmaltr** [comment]
> [app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838491/app-debug.zip)
> Could you try if this version works, because I can't find any problem and I changed the only thing which seemed different

Now the downloads doesnt even work, its always crashing.

**Comment by Dar9586** [comment]
[app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838602/app-debug.zip)

**Comment by hmaltr** [comment]
> [app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838602/app-debug.zip)

Still crashing :(

**Comment by Dar9586** [comment]
[app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838742/app-debug.zip)
Let's hope with this

**Comment by hmaltr** [comment]
> [app-debug.zip](https://github.com/Dar9586/NClientV2/files/4838742/app-debug.zip)
> Let's hope with this

**Perfect!**
All the bugs seem to be fixed and the crashes are gone.
