### ISSUE TITLE
Alternate download location doesn't persist

### ISSUE THREAD

**Issue by rlach** [Dar9586/NClientV2#185]
Changing setting "Folder Location" to memory card doesn't persist. I change it on Samsung galaxy s9+
![Screenshot_20200626-185106_NClientV2](https://user-images.githubusercontent.com/5655000/85881570-191a5400-b7de-11ea-8cbd-d4756beb349a.jpg)
And navigate to galleries. When I try to download something it gets downloaded to internal memory. When I go back into settings it's back to internal memory.

Version 2.4.7

**Comment by Dar9586** [comment]
Should be fixed in 2.4.8

**Comment by rlach** [comment]
I can confirm it works with the fix
