### ISSUE TITLE
Downloaded manga

### ISSUE THREAD

**Issue by partial-derivative** [Dar9586/NClientV2#187]
Different comics with same name are merged into one when the download is complete. This two comics use the same name after automatic simplification, behave in the folder as shown
![1593226166680](https://user-images.githubusercontent.com/67491953/85913076-2ed25c80-b864-11ea-976d-57be99f1d4f4.jpg) 
![1593226209306](https://user-images.githubusercontent.com/67491953/85913201-3f370700-b865-11ea-8531-8b607c1d80f3.jpg) The later one will skip existing picture，continue to download pictures that are not available, this leads to incomplete comics.
I divided the downloaded file into two folders and renamed the folder, but the preview in the software does not display properly.
The test is performed on Samsung Galaxy A70s
（My English is so poor....please forgive me if there is offense)

version 2.4.7

**Comment by hmaltr** [comment]
Well I suppose thats an code error. Since normally there shouldnt be multiple mangas with the same name. @Dar9586

**Comment by Dar9586** [comment]
Should be fixed in 2.4.8
