### ISSUE TITLE
nhentai/nhent.ai No entries found Error

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#188]
This is an common issue and can be fixed doing these:

Checking whether can you access them in the **browser**

If you cant access nhent.ai with/out VPN that means the website is down and its not our fault. *do not open an issue*

If you cant access nhentai.net with/out VPN try visiting the website from your browser. If you can visit the website there dont hesitate to **open an issue**

__***Please do not open duplicate issues!***__

**Comment by Kadantte** [comment]
I'm one of nhent.ai Admins the website is currently unavailable! we're working on fixing it ASAP!

**Comment by hmaltr** [comment]
> I'm one of nhent.ai Admins the website is currently unavailable! we're working on fixing it ASAP!

Woah! I wasnt expecting to some nhent.ai developer to hear us out.. Though its cool to hear it out from someone who works on it! 
Keep up the good work guys!

**Comment by py7hon** [comment]
> This is an common issue and can be fixed doing these:
> 
> Checking whether can you access them in the **browser**
> 
> If you cant access nhent.ai with/out VPN that means the website is down and its not our fault. _do not open an issue_
> 
> If you cant access nhentai.net with/out VPN try visiting the website from your browser. If you can visit the website there dont hesitate to **open an issue**
> 
> **_**Please do not open duplicate issues!**_**

Site is Working now.

**Comment by overseer1301** [comment]
No entries found in apk problem no issues connecting with the site on a browser please help
