### ISSUE TITLE
Downloaded folder naming

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#190]
Is it possible to remove these "_" and add " - " between artist and manga title？
![S00701-14292963](https://user-images.githubusercontent.com/23112624/86210867-f3bd7b00-bb3a-11ea-9fb1-f4bf2020112d.jpg)

**Comment by Dar9586** [comment]
The underscore means there was an invalid character in that position, it isn't a way to separate the artist from the title

**Comment by hohommx2015** [comment]
I knew that,i mean if the underscore could be removed and replace by "nothing"?

**Comment by Dar9586** [comment]
Fixed in 2.5.0, the old galleries must be renamed manually

**Comment by hohommx2015** [comment]
Thank you!
