### ISSUE TITLE
Wantto

### ISSUE THREAD

**Issue by Rokuyon-tokyo** [Dar9586/NClientV2#193]
Hi, thanks for the great app.

I have Favorite a lot of work.

This makes it difficult to operate.

2 4 6 12

and wants the option to change the number of views at a time.

Is this possible?
![Screenshot_20200705-003851_NClientV2](https://user-images.githubusercontent.com/56812605/86516064-99812a80-be58-11ea-8ca4-e67b0c032aa7.jpg)

**Comment by hmaltr** [comment]
@Rokuyon-tokyo I think thats possible since app had some listing options already. Btw I recommend you to **censor NSFW content** when sending an screenshot.

@Dar9586 we are on you.

**Comment by Dar9586** [comment]
Do you mean like the main page, where from the settings you can choose the columns from 1 to 4?

**Comment by Dar9586** [comment]
I don't think I understood the issue, in which way it is difficult to operate with the favorites?
