### ISSUE TITLE
Can't see comments or favorites

### ISSUE THREAD

**Issue by Bannkora** [Dar9586/NClientV2#195]
Comments aren't visible at all and the only favorites that show up are the ones i added through the app (Yes i'm logged in, and have restarted the app)

**Comment by hmaltr** [comment]
This can be a both a new problem or an code error @Dar9586 

By the way whats your app version/website selection (nhentai.net or nhent.ai)/and whether you use VPN or not.
@Bannkora

**Comment by Dar9586** [comment]
For the comments part they seems to work, could you provide an ID of a gallery where it doesn't?
Same for the online favorites, once logged they shows up, at least in the last version, in the android browser your favorites shows up?
