### ISSUE TITLE
[Feature Request] Add downloading window

### ISSUE THREAD

**Issue by hmaltr** [Dar9586/NClientV2#196]
Well when using "Download all mangas in this page" they go to the downloads and its unpractical so making an currently downloading window can be useful.

**Comment by Dar9586** [comment]
Have you some example?

**Comment by hmaltr** [comment]
This.

No matter how much are there they only appear like this [Click](https://cdn.discordapp.com/attachments/608725424092086280/730877269530378370/Screenshot_20200709-230433_NClientV2.jpg)

Thats why it would be useful.

**Comment by Dar9586** [comment]
Added in Beta 2.5.1

**Comment by hmaltr** [comment]
Gonna test it out soon.
