### ISSUE TITLE
API Suspended

### ISSUE THREAD

**Issue by PythonTryHard** [Dar9586/NClientV2#2]
Pretty much the title. Tweeted 13h ago (https://twitter.com/fuckmaou/status/1084550608097603585?s=20)

What now?

**Comment by Dar9586** [comment]
For now I'll try to parse the HTML pages from NHentai, in 1.6.5 there will be the migration

**Comment by PythonTryHard** [comment]
Iirc nHentai have CloudFlare. You might wanna check in case of the app getting flagged. Still, good luck mate since the NHBooks is no longer maintained

**Comment by Dar9586** [comment]
I just published a new version which has a temporary fix, later I will try to optimize and integrate it better

**Comment by PythonTryHard** [comment]
Bug on 1.6.4., Release APK: Page does not auto-load on both Infinity Scroll and Page Switch

**Comment by Dar9586** [comment]
Both now should be fixed.
I found other problem and fixed them, now it should be stable

**Comment by PythonTryHard** [comment]
Will do, we're kinda the only two actively participating here. I'll test the app more when I get home.

**Comment by PythonTryHard** [comment]
Welp I'm home. The loading time is kinda...awful. I'm measuring only ~170kB/s peaking at 200kB/s and the pre-loading is 3 pages (before you blame my internet I can be sure my top speed is 3.5MB/s). Is there a way to decrease load time?

**Comment by Dar9586** [comment]
In which activity it happens?
Where there is the list of the galleries, when a single gallery is showed or im the activity where you can zoom the images?
Unfortunately the image loading is managed by a library in which you give the URL and the image is loaded, I can try to check if there are bottleneck in the code.

**Comment by Dar9586** [comment]
In 1.6.7 it should work better
