### ISSUE TITLE
Can't use "Use tags from account"

### ISSUE THREAD

**Issue by Xzehnafterdark** [Dar9586/NClientV2#204]
Under the Search settings the option "Use tags from account" is greyed out and can't be used. Is this option not available anymore or do I need to do something to be able to use it?

**Comment by Dar9586** [comment]
This feature for now is not working due to the change in NHentai authentication method changed. From the next version it will be hidden until it will be reimplemented

**Comment by Xzehnafterdark** [comment]
Alright, thanks for clearing that up 👍
