### ISSUE TITLE
Files scattered throughout downloads folder.

### ISSUE THREAD

**Issue by DietMocha** [Dar9586/NClientV2#205]
Trying to clean out some space in my phone, and it's tedious digging around all the files for this app. I'm curious if it's possible to move these files to a singular subfolder of downloads, books, or somewhere else entirely by default. I feel like if I move them I'll have to reinstall.

**Comment by Dar9586** [comment]
They already are in a single folder called NClientV2 unless you change the default folder, you can move freely the folders between the different location (always in the same subfolders), but the process can't be automated and must be moved manually
