### ISSUE TITLE
Error log-in and download

### ISSUE THREAD

**Issue by viaans** [Dar9586/NClientV2#207]
When I already log in, and close the app, open it again, it's say logout
When I download the comic, choose cancel/pause, the notification won't disappear
Also, the favorite comic didn't appear from my account list

Anyway thx for the app, you make great app, it's really helping, you don't need torrent for download, you can directly download to your smartphone
I can't do much, but I will promote your app in Facebook group, you can also promote there, 
The group called "SaucePosting" it's combination between yeah you know, bunch of weebs sharing the code with memes

Group link : https://www.facebook.com/groups/239852010490012/?ref=share

![Screenshot_2020-07-30-16-51-21-03](https://user-images.githubusercontent.com/55445001/88910540-d4735400-d286-11ea-90d3-66b5323fd2c8.jpg)

**Comment by Dar9586** [comment]
It says logout because you logged in, so it is asking you if yo want to logout from your account
The favorites are only stored in local since the update to the site which make changing account galleries very difficult
I'll check better the notification problem
Thanks for the appreciation

**Comment by Dar9586** [comment]
The problem with the notification should be fixed in 2.5.4
