### ISSUE TITLE
How to set favorites online in the latest version?

### ISSUE THREAD

**Issue by RockeyX** [Dar9586/NClientV2#208]
I cannot find a bottom to set may favorites online.

**Comment by Cruga223** [comment]
I second this! The app is great but I really miss this feature :(

**Comment by Dar9586** [comment]
The feature has been removed due to the new login method which requires recaptcha, I managed only to re-enable the view of the favorite, for now seems impossible to add or removing the favorites through the app

**Comment by RockeyX** [comment]
I get it. Anyway, thanks you very much.
And by opening the page in the browser I can set my favorites online.
