### ISSUE TITLE
Download speed slow down when using WiFi

### ISSUE THREAD

**Issue by bp000169** [Dar9586/NClientV2#214]
I am using the same WiFi SSID to leave this comment and the connection is fine. But sometimes it will take over a minute to download 1 page. When i change to use my mobile data it will become ok.

**Comment by hmaltr** [comment]
Maybe it's your phone's **network preferences**? Like, when using WiFi a lot of apps use most of the **bandwidth** etc. ?
Or perhaps maybe you changed a network setting in the **app settings**?

*If not have you tried downloading different mangas? To see if there is any difference.*
