### ISSUE TITLE
I want to contribute translating the GUI to spanish

### ISSUE THREAD

**Issue by Megumin230** [Dar9586/NClientV2#215]
I want to thank you for the download all in favorites update. And in the process add to the current GUI languages. 
I don't know how to do it but if there's a way to do it without much app knowledge I'm more than happy to do it!

**Comment by Dar9586** [comment]
There are two ways to add a translation:
- Manual method
-- you download and edit this [file](https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values/strings.xml) and send it back and I will manually add it

- Git method (this method will make you appear as a contributor)
-- fork and clone this repo
-- create a folder called values-es in path app/src/main/res
-- copy this [file](https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values/strings.xml) inside values-es
-- edit that file with the translation
-- send a pull request

To edit the file you must change the text between the tag <string>EDIT_ HERE</string>
If you find a percentage sign (%d , %s etc.) they must remain as they are (only the percentage must not be changed, the rest of the text can)
