### ISSUE TITLE
No Entries found

### ISSUE THREAD

**Issue by imgregduh** [Dar9586/NClientV2#220]
tried to use the app today, "No Entries Found" kept popping up at the bottom.  I am going to assume nhentai has changed the api calls

**Comment by Dar9586** [comment]
It seems to still work
Check your tags from 'manage tags' , maybe galleries with those tags doesn't exists, if idlt doesn't fix the problem please post the url (top right in 3 circle menu there is a button 'Open in browser')

**Comment by imgregduh** [comment]
You right, I had some weird tag combinations.
