### ISSUE TITLE
Inverted colour bug

### ISSUE THREAD

**Issue by alc-droid** [Dar9586/NClientV2#223]
Hi. I found a bug where black and white pages have their colour inverted (black with white lines). In the preview it is fine but becomes inverted when reading full screen. [Error] https://imgur.com/a/wowTvuA

**Comment by Dar9586** [comment]
In the app I haven't any code to invert the color image. I tried on various devices but I can't replicate the problem. Maybe it is some compatibility issue with the library

**Comment by tizio04** [comment]
Hi, I know that this issue has been closed, but I have this problem too.
In my case, I think it's linked to the dark mode of Xiaomi's MIUI, because I tried disabling it and looks like it doesn't invert pages; when I re-enable dark mode, it randomly invert pages

**Comment by Dar9586** [comment]
> Hi, I know that this issue has been closed, but I have this problem too.
> In my case, I think it's linked to the dark mode of Xiaomi's MIUI, because I tried disabling it and looks like it doesn't invert pages; when I re-enable dark mode, it randomly invert pages

Is completely random or there are some pattern?
What android version do you have?

**Comment by Dar9586** [comment]
Could you try to use this [apk](https://github.com/Dar9586/NClientV2/files/5525529/app-release.zip). It has the latest [commit](https://github.com/Dar9586/NClientV2/commit/da7ed45c13ef00cbd5195536617b856b1f129eac)
Practically I disable the night theme inside the app (since the app theme doesn't need it for being in light or dark mode)

**Comment by tizio04** [comment]
> > Hi, I know that this issue has been closed, but I have this problem too.
> > In my case, I think it's linked to the dark mode of Xiaomi's MIUI, because I tried disabling it and looks like it doesn't invert pages; when I re-enable dark mode, it randomly invert pages
> 
> Is completely random or there are some pattern?
> What android version do you have?

Looks like it's completely random; also inverted pages remains inverted even if I close the reader and reopen it.
I have MIUI 12, on Android 10 (Xiaomi Mi Note 10 Lite)

> Could you try to use this [apk](https://github.com/Dar9586/NClientV2/files/5525529/app-release.zip). It has the latest [commit](https://github.com/Dar9586/NClientV2/commit/da7ed45c13ef00cbd5195536617b856b1f129eac)
> Practically I disabled the night theme inside the app (since the app theme doesn't need it for being in light or dark mode)

I tried it, but sadly it still invert pages...
In options I als tried switching theme, but the bug remains

**Comment by Dar9586** [comment]
I tried making other changes to disable the night theme inside the app 
[app-release_1.zip](https://github.com/Dar9586/NClientV2/files/5530848/app-release_1.zip)

**Comment by alc-droid** [comment]
The new APK has resolved the issue for me (Xiaomi Mi Mix 2S on MiUi 12) Thank you
