### ISSUE TITLE
Unable to connect to the site

### ISSUE THREAD

**Issue by SArsalanK** [Dar9586/NClientV2#226]
Unable to connect to the site

![Screenshot_2020-09-30-17-36-42-216_com dar nclientv2](https://user-images.githubusercontent.com/2125947/94686016-a58b6400-0343-11eb-8b54-14022df67051.jpg)

**Comment by hmaltr** [comment]
Please check #188 if it works for you.
If not please reply to this comment.

**Comment by SArsalanK** [comment]
> Please check #188 if it works for you.
> If not please reply to this comment.

No, it does not work for me. I have tried to run the app and in the browser with/without VPN and still the same result. Can't access it! Please check at your end. 

![Screenshot_2020-10-01-15-32-30-797_com mi globalbrowser](https://user-images.githubusercontent.com/2125947/94799100-0d9d8100-03fc-11eb-804b-a0a26f41fa1e.jpg)

**Comment by hmaltr** [comment]
I can access the website and the app works for me.

Probably its about your ISP/country banning the nhentai.net website.
Maybe try with a different VPN?
