### ISSUE TITLE
Artist tag will return false positive if the name is short and "generic" enough

### ISSUE THREAD

**Issue by PythonTryHard** [Dar9586/NClientV2#23]
Steps to recreate:

1. Go to "Manage Tag", tab "Artist" and select (in my case) "sen"
2. Cross check with <nhentai.net/artist/sen>

The tag will also list results which title/circle contain the substring "sen" 

The same bug can be triggered if you go to the doujin "Ame Ni Yadorite" (nothing special, the only doujin by sen that I remember the name) and click "sen" in the artist tag

**Comment by Dar9586** [comment]
Now it works on 1.9.1, but only if you only have one tag and you select all languages
