### ISSUE TITLE
I need to use vpn in order to use the app while i dont when connecting directly to web.

### ISSUE THREAD

**Issue by Mrsmartcoder** [Dar9586/NClientV2#234]
First time downloading this app im able to use it but after closing the app and entering it again i need to use vpn in order to use it but i dont if i goes straight to original nhentai site, is this normal ?

**Comment by hmaltr** [comment]
I don't think so but I'm not sure if i understood the last part correctly.
> but i dont if i goes straight to original nhentai site, is this normal ?
Did you mean that you can access the nhentai.net without VPN but you need to use a VPN to use the app?
