### ISSUE TITLE
[Suggestion] Option to prevent from seeing preview from app list 

### ISSUE THREAD

**Issue by flleeppyy** [Dar9586/NClientV2#235]
Though this would probably prevent screenshoting, it would be nice if there was an option in the settings to prevent seeing previews of the app from the app list, like some other apps do

Example, Wells Fargo
![Screenshot_20201011-002216_One UI Home.jpg](https://user-images.githubusercontent.com/18307183/95672681-d5aee000-0b57-11eb-9c8d-ebbdfb1bde1f.jpg)

**Comment by Dar9586** [comment]
Added in 2.6.3

**Comment by flleeppyy** [comment]
Currently on pre-release 2.6.4, ans made sure "Hide app content in multitasking" was checked. I restarted the app a couple timea and tried disabling the pin, but it still shows a preview of the app in multitasking ![Screenshot_20201108-060003_One UI Home.jpg](https://user-images.githubusercontent.com/18307183/98466971-a952a780-2187-11eb-9a8d-963675eb5a90.jpg)

Version at bottom ![Screenshot_20201108-060027_NClientV2.jpg](https://user-images.githubusercontent.com/18307183/98466985-ba031d80-2187-11eb-8baf-02cff495f212.jpg)

**Comment by Dar9586** [comment]
What android version do you have?
In 2.6.3 it worked?

**Comment by flleeppyy** [comment]
Oh...something is actually wrong with my phone because i can screenshot financial stuff. I'll restart my phone and see if it still doesn't work then

**Comment by flleeppyy** [comment]
Hmmm, yeah it's not working on my phone, but I'm going to close the issue since it's not just this app.

**Comment by Gugui322** [comment]
> Hmmm, yeah it's not working on my phone, but I'm going to close the issue since it's not just this app. 

It isn't working in my phone too.
