### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by kidman9520** [Dar9586/NClientV2#238]
After the update 2.6.2,
The notification didn't show the download progress so i headed to download section where I found the doujin that I wanted to download still loading. It goes the same to other doujin despite how speed it is my internet.

**Comment by Dar9586** [comment]
The notification only shows when effectively the download start, and sometimes it will require some time for it to begin. I tried with the same version and the code is working. Also in 2.6.2 the download routines haven't been changed. If the problem still persist you could send more info and reopen this issue
