### ISSUE TITLE
[Suggestion] Add Webtoon reading mode

### ISSUE THREAD

**Issue by Evand-smith97** [Dar9586/NClientV2#241]
Hi, thx for making this app. Btw can you make reading mode changeable? It is a good thing if you can provide webtoon reading mode.
Thank u.

**Comment by Kinuseka** [comment]
U can set the layout on the top right corner to be vertical reading

**Comment by Evand-smith97** [comment]
Yes, v2.6.3 supports vertical reading mode. Thank you all devs 👍 However i still experience some problems such as the webtoon won't fit the screen width so i need to zoom in. I hope it will be fixed in the next update. For referrence I use zenfone max pro m2

**Comment by Kinuseka** [comment]
The 2.6.3 vertical reading mode isnt what I meant. There is another way to read vertically more comfortably, which is before u click any image to open the read mode. U can set the preview mode to become vertical on the top right. There are boxes on there and u can tap it to change the preview format, tap it till its Vertical mode
