### ISSUE TITLE
Nhentai.net banned in france

### ISSUE THREAD

**Issue by error7404** [Dar9586/NClientV2#248]
Nhentai.net is now banned in France and replaced by nhentai.to can you add that function please

**Comment by Yashirow** [comment]
Yeah sad :((

**Comment by Dar9586** [comment]
Unfortunately nhentai.to can't be used. It works differently from nhentai.net, even if they look similar
For example:
https://nhentai.net/search?q=language:"english" shows the english galleries 
meanwhile
https://nhentai.to/search?q=language:"english" has 0 entries

**Comment by error7404** [comment]
I guess it's DNS time (DNS 1.1.1.1 works)

**Comment by Yashirow** [comment]
So we can't use the app anymore ?

**Comment by error7404** [comment]
just download 1.1.1.1 on the playstore 
https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US&gl=us

**Comment by Gugui322** [comment]
**Why not use a VPN? Is easy, the socialist french government afraid vpns**.

**Comment by error7404** [comment]
1.1.1.1 DNS works like a VPN it is based in Belgium so no block
