### ISSUE TITLE
Return to previous page sometimes doesn't work

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#25]
Search a artist and enter the artist's page and open a gallery,and return to the artist's page,and return again(this is where the issue happens(sometimes return doesn't work),I have to force close the app and open again.

**Comment by panslothda** [comment]
For me this happens on every tag or artist i open. Whenever you click on another tag it doesnt let you go back. Ever

**Comment by hohommx2015** [comment]
You're right.I've noticed that too.

**Comment by Dar9586** [comment]
Fixed on 1.9.0

**Comment by hohommx2015** [comment]
@Dar9586  Thank you!
