### ISSUE TITLE
Please add an option for custom download (or zip) location

### ISSUE THREAD

**Issue by nthtimes** [Dar9586/NClientV2#259]
I want to use other reader to watch downloaded comics. However, In Android 11, Google restricted other apps access android/data/AppName.

**Comment by nulleqn** [comment]
me too

**Comment by nthtimes** [comment]
Custom path is works normally, but pages preview doesn't work in custom path.

![Screenshot_20210203-105907410](https://user-images.githubusercontent.com/50926809/106866878-f18e5100-6707-11eb-9fd6-1c4d5aab675e.png)
