### ISSUE TITLE
Unable to connect to the site      -      RETRY

### ISSUE THREAD

**Issue by maki1999** [Dar9586/NClientV2#261]
When i open the App i immediately get a notification saying, "Unable to connect to the site" and i can't see any mangas. 
When i try to log in into my account there is also just a blank page and i can't login.
I tried using a VPN and then it worked like it should do.
Still very annoying since i basicly never use a VPN

Here the screenshots:

![Screenshot_20210102-015828_NClientV2](https://user-images.githubusercontent.com/76855797/103448750-14a78a00-4c9e-11eb-8642-1c7e4ade95c8.jpg)

![Screenshot_20210102-015837_NClientV2](https://user-images.githubusercontent.com/76855797/103448753-1cffc500-4c9e-11eb-8a27-ce56aa274c4d.jpg)

**Comment by Dar9586** [comment]
Can you connect to the site without VPN?
This app connects directly to nhentai.net, so usually if from the app you have access problem then you will have problem also to access the site
