### ISSUE TITLE
Unable to recognize downloaded manga when don't have zero in filename

### ISSUE THREAD

**Issue by tarzanchemgio** [Dar9586/NClientV2#262]
The app will not show my episode in Download Manga screen if picture name is `01.jpg` instead of `001.jpg`
![Screenshot_2021-01-07-18-33-06-75](https://user-images.githubusercontent.com/47100782/103888161-d6cfb900-5116-11eb-941c-29c1fc94e72d.jpg)
![Screenshot_2021-01-07-18-34-11-82](https://user-images.githubusercontent.com/47100782/103888230-fff04980-5116-11eb-991e-a59c1d410a15.jpg)
Pictures are not presented just because of a zero letter (っ˘̩╭╮˘̩)っ

**Comment by Dar9586** [comment]
the app has created pages with only 2 digits or it has been renamed?

**Comment by tarzanchemgio** [comment]
> the app has created pages with only 2 digits or it has been renamed?

They were downloaded from nhentai.net so I supposed it is the second case

**Comment by tarzanchemgio** [comment]
@Dar9586 Hello again, I saw new release that tried to fix reported bug. It did resolve 50% the problem (◍•ᴗ•◍)❤
App now can recognize number of pages but still cannot show images that name with 2 digits like `01.jpg` and so on. Here is my screen looks like:

![Screenshot_2021-01-18-15-32-30-21](https://user-images.githubusercontent.com/47100782/104891666-d8fe0700-59a3-11eb-9a62-dd8e02f04d68.jpg)
![Screenshot_2021-01-18-15-32-43-06](https://user-images.githubusercontent.com/47100782/104891675-dac7ca80-59a3-11eb-9430-96c0fb23b5ca.jpg)

New Android update recently block user out from `Android/data` so I capture my downloaded folder from PC here (~‾▿‾)~

![Untitled](https://user-images.githubusercontent.com/47100782/104892078-53c72200-59a4-11eb-8be7-49e2c14df122.jpg)

Since this update, I think we really need abilities to select more folders for Downloaded Manga than 2 default options.
Note that if we rename them like `001.jpg` things will be okay. 
Anyway, your work is awesome :)))
