### ISSUE TITLE
Unable to connect to the site RETRY

### ISSUE THREAD

**Issue by GensokyoIsReal** [Dar9586/NClientV2#269]
Can't use the client. It just loads infinitely until a "Unable to connect to the site RETRY" error pops. 
YES, the website does work in my phone's regular browser and I can access it from here. I must add that the client was working fine a few months ago, I do not know exactly when it stopped working.
![20210122_082500](https://user-images.githubusercontent.com/77827609/105460090-8fefd080-5c8b-11eb-8aa3-72f113a5f1d9.jpg)

**Comment by Dar9586** [comment]
Which android version are you using?

**Comment by babaika228** [comment]
Same on mine phone. Site is working, browser is Mi Browser. Android 10 (MIUI 12)

**Comment by Dar9586** [comment]
Could you try to use custom DNS instead of the one of your ISP
I would try with

**Comment by GensokyoIsReal** [comment]
Just tried that, both Cloudflare and Google, doesn't work for both. 
My Android version is 10
