### ISSUE TITLE
请问这种情况怎么处理啊？

### ISSUE THREAD

**Issue by sakura503** [Dar9586/NClientV2#271]
今天打开发现首页无显示，无论切换排序类型，还是切换地区，首页都是无显示，请问阁下有什么办法解决吗？
![Screenshot_2021-01-28-21-49-07-818_com dar nclientv2](https://user-images.githubusercontent.com/64682317/106147522-eb055400-61b2-11eb-8fff-535d0efca496.jpg)

**Comment by reiuyfan** [comment]
Have you tried using a proxy？

**Comment by hmaltr** [comment]
If translate worked correctly can you try instructions in #188? If it doesn't work please reply to this comment. *English is preferred*
