### ISSUE TITLE
issue on downloads tab

### ISSUE THREAD

**Issue by aligdr** [Dar9586/NClientV2#278]
App crashs on openning dowloads installing the new update

**Comment by Dar9586** [comment]
Probabily duplicate of #277, if it is the case I reloaded the apk with the fix
https://github.com/Dar9586/NClientV2/releases/download/2.6.9/NClientV2.2.6.9.Release.apk
https://github.com/Dar9586/NClientV2/releases/download/2.6.9/NClientV2.2.6.9.Debug.apk
