### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by PegadaDLancha** [Dar9586/NClientV2#290]
the app drained 60% of my phone batery in in less then 2 hours in background

**Comment by Dar9586** [comment]
I do't think the cause of the battery drain is this app. The app in background for a long time are the downloads, the creation of zips and the creation of pdf, but all of them must be explicitly requested by the user and there is a notification. Then there is the creation of the tags DB which could be battery expansive but it is done once every few months.
Usually the system provides data about battery consummation, could you send screenshot about it?

**Comment by PegadaDLancha** [comment]
![Screenshot_20210207-223011](https://user-images.githubusercontent.com/78657121/107166352-7ab9b800-6994-11eb-91a8-6b8f9642dc99.jpg)

**Comment by PegadaDLancha** [comment]
![Screenshot_20210207-173415](https://user-images.githubusercontent.com/78657121/107166383-9329d280-6994-11eb-8c1e-868cc75f6ee8.jpg)

**Comment by PegadaDLancha** [comment]
i leaved my home with 55% battery, then after like 1,5 hours it was at 25%

**Comment by Gugui322** [comment]
> i leaved my home with 55% battery, then after like 1,5 hours it was at 25%

Lol weak battery
