### ISSUE TITLE
The scroll bar is too short

### ISSUE THREAD

**Issue by anmengyuan** [Dar9586/NClientV2#291]
Too many favorites galleries(downloaded galleries) cause scrollbars to get shorter.
Sorry, my English is not very good.
thanks for the great app.
![A-22](https://user-images.githubusercontent.com/65168599/107256728-d2c7eb80-6a74-11eb-87c9-3829900db355.jpg)

**Comment by Dar9586** [comment]
Should be fixed in 2.7.6

**Comment by anmengyuan** [comment]
Thank you very much.
