### ISSUE TITLE
Opening from web browser causes a force close.

### ISSUE THREAD

**Issue by coderkei** [Dar9586/NClientV2#294]
Issue:
Opening manga from the website version of nhentai into the NClient app from a browser.

Expected behavior:
In version 2.6.9 I could use the "Open in app" function of Firefox Mobile to open any nhentai manga page and it would open that manga in the NClient app.

Actual behavior:
In version 2.7.1, trying to do this now just makes the app open and then immediately force close. The only way to get the manga to show in the app is to manually search the index number inside the app.

I also tried from Chrome, where it shows the available apps to open links in, and when I select NClientV2, the same force close issue happens.

Running Android 10 on an Oppo Reno, I am using the F-Droid version of the app, 2.7.1.

**Comment by Dar9586** [comment]
I think it is a problem which was already fixed since in 2.7.7 the galleries are opening normally (tried with 177013 and 347365, maybe it only affects some id), wait until F-Droid updates the app to 2.7.6 (last stable)

**Comment by coderkei** [comment]
Okay thank you. If it works once I get the update, I'll close this issue.
