### ISSUE TITLE
给我解释一下为什么中文漫画在收藏页面里显示的国旗是中华民国的国旗

### ISSUE THREAD

**Issue by MCredbear** [Dar9586/NClientV2#299]
给我解释一下为什么中文漫画在收藏页面里显示的国旗是中华民国的国旗

Why do the Chinese comics in favourite galleries show flag of the Republic Of China instead of the People's Republic Of China? I want an explanation.

**Comment by Dar9586** [comment]
Fixed in beta 2.7.8

**Comment by LainNetWork** [comment]
最近我切换中文不知道为什么在Nclient里搜不了中文漫画了。。不知道你有没有这个问题？

**Comment by fengxueguguzhu** [comment]
鬼子会安什么好心
