### ISSUE TITLE
Adding optione to use volume buttons to switch page

### ISSUE THREAD

**Issue by panslothda** [Dar9586/NClientV2#3]
Pretty much as title says. Would it be possible to add an option to use the volume keys to turn pages?

**Comment by Dar9586** [comment]
Added in 1.6.7

**Comment by panslothda** [comment]
Awesome thank you so much for this :)

Small addition to this would it be possible to add an option to this to switch directions around? As some will prefer it with volume key down to turn page forward and some for how it is right now.

**Comment by Dar9586** [comment]
I could make up for forward and down for backward when in portrait and viceversa in landscape

**Comment by panslothda** [comment]
Best would probably be if people could set it in settings if up was forward or backwards and same for down. So a togle for which direction so to say. But of course that would just be an extremely awesome option but not necessary at all :) the function itself is already really nice to have :)

**Comment by Dar9586** [comment]
Added in 1.6.8
