### ISSUE TITLE
Is this app abandoned?

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#30]
Just curious

**Comment by Zunon** [comment]
@hohommx2015 it doesn't seem to be.

**Comment by hohommx2015** [comment]
> @hohommx2015 it doesn't seem to be.

I hope so,but the dev isn't active for almost 3 months now

**Comment by Dar9586** [comment]
Sorry for the waiting, in this period I was unable to continue updating the app.
Now the problem is fixed so I will restart to updating it.

**Comment by hohommx2015** [comment]
Nice to hear it
