### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by viaans** [Dar9586/NClientV2#304]
I don't know how to say it, you can clearly see in the picture
First pic is kinda blurry
But when I click the picture like in second pic, it have good quality
![Screenshot_2021-03-27-10-14-37-23_8dc4a708c34f1c510344fe919321c07b](https://user-images.githubusercontent.com/55445001/112708741-60a54c00-8ee6-11eb-9f45-d268074be8df.jpg)

![Screenshot_2021-03-27-10-14-40-95_8dc4a708c34f1c510344fe919321c07b](https://user-images.githubusercontent.com/55445001/112708773-8c283680-8ee6-11eb-885f-63fd819e1391.jpg)

**Comment by Dar9586** [comment]
Fixed in 2.8.0
