### ISSUE TITLE
[suggestion] please optimize the image quality of "convert to PDF" function

### ISSUE THREAD

**Issue by mxu0713** [Dar9586/NClientV2#320]
Today, I found this function and tried it, but I think the quality of the image converted to PDF is too poor. When the image is not enlarged, it will be blurred by naked eye. If you zoom in again, there will be obvious mosaic.
Although I know that this may be due to the limited storage space of some users, my personal storage space is very sufficient.
So can you improve the quality of the converted image, or add an option to adjust the quality of the converted image?

**Comment by mxu0713** [comment]
Thank you very much for adopting my suggestion. Now the display quality of PDF is normal, but the converted PDF file is sometimes missing. Thank you very much for adopting my suggestion. Now the display quality of PDF is normal, but there is a new problem. The converted PDF file sometimes lacks the last few pages.
Please repair it again.

**Comment by Dar9586** [comment]
Fixed in 2.8.1
