### ISSUE TITLE
Images unload when going scrolling through pages

### ISSUE THREAD

**Issue by flleeppyy** [Dar9586/NClientV2#327]
https://user-images.githubusercontent.com/18307183/125162981-d1900d00-e13f-11eb-99d3-1862768332ca.mp4

**Comment by hmaltr** [comment]
This probably has to do with "Image Preloading". Set the setting to 1 for a temporary fix while @Dar9586 fixes it.

**Comment by Dar9586** [comment]
This should be fixed in 2.8.1
