### ISSUE TITLE
New version killed app

### ISSUE THREAD

**Issue by Zodic-leo** [Dar9586/NClientV2#330]
After I updated to 2.8.1 whenever I swipe to the next page of a gallery it pulls me out of the gallery

**Comment by Dar9586** [comment]
I tried on Android 16, 29 and 30 but I couldn't reproduce. Which android version do you have? Also do you have some particular setting enabled?

**Comment by Zodic-leo** [comment]
I've got android 10 and I don't have any setting that would mess with that type of thing. I've only really changed 2 settings, I set a pin and hid content from multitasking

**Comment by Zodic-leo** [comment]
I just checked the app again and it seems like it managed to fix itself. I've done nothing to fix it but it works fine now
