### ISSUE TITLE
Have problem downloading gallery

### ISSUE THREAD

**Issue by mushsoooup** [Dar9586/NClientV2#333]
This happens comstantly。Only in a few times it works properly

**Comment by hmaltr** [comment]
Can you send a screenshot of it? I don't have any problems downloading galleries.

**Comment by gasaimaple** [comment]
![image](https://user-images.githubusercontent.com/42872701/125865332-4010be00-3e75-4243-afcb-2f3c0d380d3e.png)

**Comment by gasaimaple** [comment]
![125865332-4010be00-3e75-4243-afcb-2f3c0d380d3e](https://user-images.githubusercontent.com/42872701/125865843-00da38c8-2f30-4cc4-8b2a-9de68e49688a.png)
There is no problem with my network since i can load and read them online

**Comment by z0dkc** [comment]
Having the same problem. I can read online just fine but downloads don't seem to start.

I thought it was a storage permission issue at first but when I went to go look at permissions in settings it's allowed.

**Comment by gasaimaple** [comment]
> Having the same problem. I can read online just fine but downloads don't seem to start.
> 
> I thought it was a storage permission issue at first but when I went to go look at permissions in settings it's allowed.

I tried the latest DEBUG version and it works fine for NOW.
I'm hoping that it won't break just like the release version.

**Comment by gasaimaple** [comment]
> Can you send a screenshot of it? I don't have any problems downloading galleries.

And the release version worked fine in the beginning, it broke somehow.
