### ISSUE TITLE
Folder name issue

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#34]
Certain folders creat separate subfolder for pics,like this one:
![IMG_3dfc1ac3fbf774fe80279944ea152839](https://user-images.githubusercontent.com/23112624/69489888-f4738d80-0e44-11ea-9563-625421f210e6.jpg)
And doujin/manga like this would not show in Downloaded Manga section

The correct folder name of that doujin should be like this
![超级截屏_20191124_125040](https://user-images.githubusercontent.com/23112624/69489929-6b108b00-0e45-11ea-9db6-e1361c7e2bec.png)

**Comment by Dar9586** [comment]
Should be fixed in 1.9.3. 
All the manga downloaded with this version should not have this problem.
Added also a fix which compact the old galleries

**Comment by hohommx2015** [comment]
Thank you!
