### ISSUE TITLE
Page quantity

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#37]
It would be a nice touch to the app to have page quantity displaying below Category like the site
![IMG_e713cf87c7526ba74c7af82fde9f2f5c](https://user-images.githubusercontent.com/23112624/69741952-91fae580-1101-11ea-8547-422a8f37524c.jpg)

**Comment by Dar9586** [comment]
Added, I don't know how I forgot this

**Comment by hohommx2015** [comment]
That's fast! Thanks!
