### ISSUE TITLE
Hide app in multitasking doesn't work on Android 11

### ISSUE THREAD

**Issue by Asneb** [Dar9586/NClientV2#384]
When this option is activated on Android 11 it doesn't do anything

**Comment by hmaltr** [comment]
It works for me (also Android 11),
Whats your device model?
Have you tried turning the setting on and off?
Does this work in other apps? (Such as incognito mode in chrome, it hides itself when you are in an incognito page)

**Comment by Asneb** [comment]
Moto G 5g
Yes
Works in Chrome and Hendroid (makes that function available)

Em qua., 26 de jan. de 2022 16:01, hmaltr ***@***.***>
escreveu:
