### ISSUE TITLE
No entries found

### ISSUE THREAD

**Issue by apfellor** [Dar9586/NClientV2#386]
First of all i must say that I love the apk you made. But recently i have a bug where i cant find doujins anymore because when i go to the mainsite or online favorites it says "no entries found" I can only look at the ones that I have in my favorite galleries. It would be lovely if you can find a way to patch the bug. So I can use the app again.

**Comment by apfellor** [comment]
Everything works normal again

**Comment by Notarin** [comment]
I'm having the same issue, i wonder if it has something to do with the api
