### ISSUE TITLE
Features and enhancements request

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#39]
There are 4 in total,sorry for my poor English first,hope these pics can help.

1. Gallery info alignment
![Project_1_1](https://user-images.githubusercontent.com/23112624/69878064-74588800-1289-11ea-9af3-9381bcce68ff.png)

2.Add option to allow user to choose column quantity in both portrait and landscape,personally i request a 3 columns option in portrait
![1575035832472](https://user-images.githubusercontent.com/23112624/69878228-f34dc080-1289-11ea-94b1-d87f80e3151f.jpg)

3.Add option to turn on/off gallery name
![IMG_9e09ff6f9436daad547820e0bb93b17a](https://user-images.githubusercontent.com/23112624/69878671-32c8dc80-128b-11ea-81c3-9bb8b5647949.jpg)

4.Shorten the distance between two page rows and add page number displaying to each page.
![IMG_99cc9153c0984f3512371e1e555b3c08](https://user-images.githubusercontent.com/23112624/69878826-918e5600-128b-11ea-898c-d6adf97d0db9.jpg)

**Comment by ZerOri** [comment]
该意见对提升app的体验还是有点帮助的，特别是3和4项

**Comment by hohommx2015** [comment]
@Dar9586 
Thanks,version 1.9.8 solved 1 3 4 and only "3 column in portrait" remains to be done.

**Comment by Dar9586** [comment]
Added 3 column while in portrait in 1.9.9

**Comment by hohommx2015** [comment]
Perfect,thank you.
