### ISSUE TITLE
The app crashes when I open the settings

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [Dar9586/NClientV2#397]
Lastest version
Japanese
Android11 crdroid
https://paste.crdroid.net/pN19Z5

**Comment by GalaxyNight** [comment]
I changed the system language to English, and it worked fine.

**Comment by YaoReTian** [comment]
I've had the same problem, but I decided to change the language in the app settings, so I am completely unable to reach the settings without reinstalling the entire app...

**Comment by Dar9586** [comment]
Should be fixed in latest version. The format string had  '。' instead of the '.' character
