### ISSUE TITLE
SDK17

### ISSUE THREAD

**Issue by Kadantte** [Dar9586/NClientV2#4]
Hi,
Could you please build the app for Android 4.2.2 ?!

**Comment by Dar9586** [comment]
I added support until API level 14 in 1.7.0
Unfortunately I can't test it, if there are problems make me know

**Comment by Kadantte** [comment]
Thank's i'll try it right now.

**Comment by Kadantte** [comment]
For now i can install it , but when i open the app it open and close after that without showing any Errors.

**Comment by Dar9586** [comment]
I tried with the emulator and now it with 1.7.2 should work better

**Comment by Kadantte** [comment]
Worked , Thank's a lot :D .
