### ISSUE TITLE
I want to help translate NClientV2 into Chinese, what should I do?

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#40]
I am a Chinese user,I like this app and want to help translate it into Chinese, what should I do?

**Comment by Dar9586** [comment]
You can both:

1. Clone and pull
   - Clone the repository
   - Edit the file: https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values-zh/strings.xml
   - Create a pull request that I will accept
2. Download and edit
   - Download the file: https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
   - Upload somewhere and share here the link
   - In this case I will manually merge that file

**Comment by ZerOri** [comment]
> You can both:
> 
> Clone and pull
> 
> Clone the repository: https://github.com/Dar9586/NClientV2.git
> Edit the file: https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values-zh/strings.xml
> Create a pull request that I will accept
> 
> 
> Download and edit
> 
> Download the file: https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
> Edit the file, upload somewhere and share here the link
> In this case I will manually merge that file
> 
> 
> 
> Editing only requires to replace the text between the two pair of brackets
> From: <string name="..">ENGLISH TEXT</string>
> To:     <string name="..">CHINESE TEXT</string>

I see,thank you~

**Comment by ZerOri** [comment]
> You can both:
> 
> Clone and pull
> 
> Clone the repository: https://github.com/Dar9586/NClientV2.git
> Edit the file: https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values-zh/strings.xml
> Create a pull request that I will accept
> 
> 
> Download and edit
> 
> Download the file: https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
> Edit the file, upload somewhere and share here the link
> In this case I will manually merge that file
> 
> 
> 
> Editing only requires to replace the text between the two pair of brackets
> From: <string name="..">ENGLISH TEXT</string>
> To:     <string name="..">CHINESE TEXT</string>

https://drive.google.com/file/d/1zqkFk36DP3GVMk2gH9_E8r__dGYySKQb/view?usp=sharing

**Comment by ZerOri** [comment]
> You can both:
> 
> Clone and pull
> 
> Clone the repository: https://github.com/Dar9586/NClientV2.git
> Edit the file: https://github.com/Dar9586/NClientV2/blob/master/app/src/main/res/values-zh/strings.xml
> Create a pull request that I will accept
> 
> 
> Download and edit
> 
> Download the file: https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
> Edit the file, upload somewhere and share here the link
> In this case I will manually merge that file
> 
> 
> 
> Editing only requires to replace the text between the two pair of brackets
> From: <string name="..">ENGLISH TEXT</string>
> To:     <string name="..">CHINESE TEXT</string>
Hi,here is the translated files:
https://drive.google.com/file/d/1zqkFk36DP3GVMk2gH9_E8r__dGYySKQb/view?usp=sharing

I did my best to improve the translated text, but may still be unavoidable mistake. Please send me the app to check for omissions before update.

**Comment by Dar9586** [comment]
New version uploaded on [this link](https://drive.google.com/open?id=1kuq5bMFiz7NC7elPD_vugt_BhnR3ew2g)
Others settings have been added, so they aren't translated, you can find them at the end of the updated file ([here](https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml))

**Comment by ZerOri** [comment]
> New version uploaded on this link
> Others settings have been added, so they aren't translated, you can find them at the end of the updated file (here)

There is the new file,revised some translations and punctuation.
strings_cht.xml is the Chinese Traditional text.
[](https://drive.google.com/drive/folders/1svm75BQbyisZ1oDLNA2iKkUH737vhWdJ?usp=sharing)

But some places still don't shown Chinese.

**Comment by Dar9586** [comment]
Added the new strings:
The traditional now is at https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-ch/strings.xml
The simplified is at https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
The new version is at https://drive.google.com/open?id=10qItoAP5F5GS3g4xtFoZ8dssMylI67e9

**Comment by ZerOri** [comment]
> Added the new strings:
> The traditional now is at https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-ch/strings.xml
> The simplified is at https://raw.githubusercontent.com/Dar9586/NClientV2/master/app/src/main/res/values-zh/strings.xml
> The new version is at https://drive.google.com/open?id=10qItoAP5F5GS3g4xtFoZ8dssMylI67e9

OK,I did it~
