### ISSUE TITLE
no entries found

### ISSUE THREAD

**Issue by error40436194391** [Dar9586/NClientV2#403]
no tags but still no entries found

**Comment by Notarin** [comment]
This is a duplicate of #402

**Comment by Lucaelgar** [comment]
> This is a duplicate of #402

shut up you tweep

**Comment by Notarin** [comment]
> > This is a duplicate of #402
> 
> shut up you tweep

Take a chill pill kid. This isn't a forum this is a fucking GitHub issue. Go elsewhere with that shit.

**Comment by Lucaelgar** [comment]
> > > This is a duplicate of #402
> > 
> > 
> > shut up you tweep
> 
> Take a chill pill kid. This isn't a forum this is a fucking GitHub issue. Go elsewhere with that shit.

yeah that's true
