### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by prettend-s** [Dar9586/NClientV2#404]
![Screenshot_2022-03-06-12-08-11-31_8dc4a708c34f1c510344fe919321c07b](https://user-images.githubusercontent.com/99039892/156908832-3abc5f21-ee9b-4b86-b2ec-8c9298c1d6e0.jpg)

**Comment by Notarin** [comment]
This is a duplicate of #402

**Comment by Notarin** [comment]
please label duplicate, ty
