### ISSUE TITLE
Client won't load any doujin

### ISSUE THREAD

**Issue by Lucaelgar** [Dar9586/NClientV2#405]
basically what the title says whenever I go on the home page it just says so entries found. I've done pretty much everything I could think of to try and fix it, I restarted the app, cleared the cache then I just completely uninstalled and reinstalled it but it still doesn't work. Weirdly I could load doujin from my liked section so idk

**Comment by Yoake2000** [comment]
I think the cloudflare DDOS protection may have affected the app's access. I can't confirm if that's really the case but the problem appeared at the time when the website started having the browser checking process

**Comment by Notarin** [comment]
This is a duplicate of #402

**Comment by Lucaelgar** [comment]
> This is a duplicate of #402

ok
