### ISSUE TITLE
The application does not start the site.

### ISSUE THREAD

**Issue by byopera** [Dar9586/NClientV2#421]
When I log in to the application, I keep getting the "no results found" error. Even refreshing the page or translating the translation language doesn't help. Despite the update, the problem did not go away. I request this issue to be fixed

![Screenshot_20220429-221240](https://user-images.githubusercontent.com/104650983/166023563-bba3013e-3773-4131-a4e3-0a210b9ede12.png)

**Comment by markpaul099** [comment]
#416
