### ISSUE TITLE
API error : "No entries Found"

### ISSUE THREAD

**Issue by Farbersaw** [Dar9586/NClientV2#427]
We're having the API error again where the app cannot find any entries possibly due to nhentai adding the Ddos cloud flare stuff 
![Screenshot_20220501_172402_com dar nclientv2](https://user-images.githubusercontent.com/76242135/166144641-b1edd3b0-5c30-419f-80b7-d07c46420573.jpg)

![Videoframe_20220501_172859_com huawei himovie overseas](https://user-images.githubusercontent.com/76242135/166144836-8ed62502-dc55-437b-b6bc-7c441d8b25e2.jpg)

**Comment by FC-TFO** [comment]
yes，me too

**Comment by DatBoiOrly** [comment]
yeah i'm getting the same issue also
this is super sucky IMO since the official app/website is poor in comparison to this custom version, i hope it gets fixed soon!

**Comment by Marek1807** [comment]
Same
