### ISSUE TITLE
V1.9.8 doesn‘t work on Android 10

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#43]
V1.9.8 doesn‘t work on Android 10…Same for other versions(Android 5.1 and 6.0)

**Comment by ZerOri** [comment]
Looks like something went wrong with app.

**Comment by Dar9586** [comment]
Updated the version 1.9.8 with the fixed APK, I decided not to create a new version because it was just a line of code

**Comment by ZerOri** [comment]
> Updated the version 1.9.8 with the fixed APK, I decided not to create a new version because it was just a line of code

The new release is buggy again. Clicking on the downloaded manga will crash.

**Comment by ZerOri** [comment]
![TIM图片20191202111719](https://user-images.githubusercontent.com/46775615/69928053-63ac4a00-14f5-11ea-9963-4f3abab3e9e5.jpg)

And the tags of manga detail page still has no Chinese.

**Comment by Dar9586** [comment]
Translation fixed, now should work on Android 10 too
