### ISSUE TITLE
NclientV2 error

### ISSUE THREAD

**Issue by JotaG09** [Dar9586/NClientV2#434]
Sometimes when I enter the app it says "no entries found" and it doesn't show any doujinshis (the text is in Spanish but it's still the same) 
![Screenshot_2022-05-02-09-55-35-959_com dar nclientv2 debug](https://user-images.githubusercontent.com/104757010/166202527-fc03e52a-42f2-4683-9d76-9061f98331cd.jpg)

**Comment by hmaltr** [comment]
Check #433
