### ISSUE TITLE
Cant load the page

### ISSUE THREAD

**Issue by kurniawankamisaputra** [Dar9586/NClientV2#441]
![Screenshot_20220502-210039_NClientV2](https://user-images.githubusercontent.com/34050292/166246735-a295f7a1-6b38-4587-b489-22b745ee7c72.png)

App Always show no entries found, btw i use private DNS from Cloudflare and Quad9

**Comment by hmaltr** [comment]
Check #433

**Comment by UltraN0VA** [comment]
This is due to the ddos protection from the nhentai site, we'll have to wait for a bypass
