### ISSUE TITLE
No Entries

### ISSUE THREAD

**Issue by FrankenberryJr** [Dar9586/NClientV2#443]
I opened the app to see "no entries found". Everything was normal the last time I used the app. I have some tags blacklisted, but I don't have any check marked/searched for. My favorites list and other tag lists appear, just not the landing page, random gallery, nor searching. The galleries themselves are fine once I select one from my favorites.

Tried clearing cache and logging out already. 2.9.1 stable release on Android 12.

**Comment by hmaltr** [comment]
Check #433

**Comment by UltraN0VA** [comment]
This is due to the ddos protection from the nhentai site, a lot of us are experiencing this and waiting for a bypass

**Comment by futurex894** [comment]
It seems that the problem has been solved automatically.
