### ISSUE TITLE
no entries found

### ISSUE THREAD

**Issue by hhpy123** [Dar9586/NClientV2#455]
![Screenshot_20220522-075801](https://user-images.githubusercontent.com/100397618/169672693-827a7fda-3f88-42f2-95ee-b372039289bb.jpg)

**Comment by notorly1337** [comment]
Same. Tried previous versions of 2.9.1 and 2.9.0. Both have save error. Seems like it might be related to the site and how it's parsing the data as a whole. Maybe the site is trying to block attempts at apps like this one from working as intended. Pure speculation on my part.

**Comment by 1-minute-to-midnight** [comment]
https://github.com/Dar9586/NClientV2/issues/433
