### ISSUE TITLE
This app will soon become obsolete if cloudflare issue is not fixed

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [Dar9586/NClientV2#457]
The cloudflare issue is a major issue and if it is not fixed, the app will be useless. This used to be a rare issue sometime back but it has become more common as of late. I urge the developer to please find a workaround for this issue as I really love this app and don't want to see it die.

**Comment by maki1999** [comment]
Does the cloudfare issue have something to do with the 
"No entries foune" problem?

**Comment by 1-minute-to-midnight** [comment]
yup

**Comment by Remilya** [comment]
Very unfortunate truth

**Comment by Remilya** [comment]
Finnaly working again

**Comment by Remilya** [comment]
I found myself again
