### ISSUE TITLE
中国

### ISSUE THREAD

**Issue by LFW06** [Dar9586/NClientV2#459]
无法加载页面，显示无法加载条目

**Comment by sixyang** [comment]
我也遇到这个问题，换了梯子也不行

**Comment by ArnoClare** [comment]
在 issue 433 有回复，由于 nhentai 给网站添加了 cloudflare 后，app 无法获取数据导致的。
开发说关于“找不到条目”请勿再开 issue 了，只能等什么时候修复了。
