### ISSUE TITLE
In version upper than 1.9.2 searching by code not work. And please add feature download from page xxx to page xxx because many doujin in one tittle have more than one story.

### ISSUE THREAD

**Issue by deardian20** [Dar9586/NClientV2#46]
I hope i can search again with code and download Page by page.
Thx

**Comment by hohommx2015** [comment]
Great feature,user don't have to download whole gallery.

**Comment by Dar9586** [comment]
Fixed using id for searching, the bulk downloading will be added in future updates with #27

**Comment by deardian20** [comment]
Thank you very much its very fast
