### ISSUE TITLE
Invalid Response (again)

### ISSUE THREAD

**Issue by CaptainRightHandMan** [Dar9586/NClientV2#464]
The other day, it had invalid response. Yesterday, no invalid response. Today, there is an invalid response and the recent home page does not load.

**Comment by KidzEz** [comment]
Try clear app data and cache. It works for a while, but when it show invalid response again you must clear app data again.

**Comment by viaans** [comment]
Same here

**Comment by viaans** [comment]
Delete cache, it's has to do something with the cloudflare

**Comment by Nikki-Devil** [comment]
Same here even after the update (clear cach don't solve the problem)

**Comment by Schw1** [comment]
Try this:
1. Delete Cache
2. Log out (if you logged in)
3. Log in
4. Press on the logo
5. Wait until you get on the Homepage and Cloudflare disappear
6. Go back to the app, is should working again

It worked for me.

**Comment by ILFforever** [comment]
> Try this:
> 
> 1. Delete Cache
> 2. Log out (if you logged in)
> 3. Log in
> 4. Press on the logo
> 5. Wait until you get on the Homepage and Cloudflare disappear
> 6. Go back to the app, is should working again
> 
> It worked for me.

Actually worked!! Thanks a lot :>

**Comment by Nikki-Devil** [comment]
> Try this:
> 1. Delete Cache
> 2. Log out (if you logged in)
> 3. Log in
> 4. Press on the logo
> 5. Wait until you get on the Homepage and Cloudflare disappear
> 6. Go back to the app, is should working again
> 
> It worked for me.

Worked ^^

**Comment by Remilya** [comment]
Presing login and waiting worked
