### ISSUE TITLE
"Invalid response" after updating the app

### ISSUE THREAD

**Issue by Marrrro** [Dar9586/NClientV2#473]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System version:

* NHentai link (if relevant):

**Comment by KhanSimeoni** [comment]
I'm getting this as well, I'm pretty sure it's because for whatever reason cloudflare won't validate the app. I'd just use an earlier version for now
