### ISSUE TITLE
Invalid response on v2.9.7

### ISSUE THREAD

**Issue by chanhh01** [Dar9586/NClientV2#477]
I heard that many people had this issue during 2.9.6 and so was I, but as I see some users saying the problems went away, I still don't see mine fixed... It's still getting invalid response after updating to 2.9.7

The browser version is working fine, so is it API issue?

![Screenshot_2022-06-29-09-35-46-843_com dar nclientv2](https://user-images.githubusercontent.com/84566394/176332270-6e3c6f73-231f-4831-aba8-2072d1987c54.jpg)

**Comment by diegosace2000** [comment]
Yeah I still having that

**Comment by Tr4velt0Here** [comment]
clear cookies and restart the app

**Comment by Karo0321** [comment]
> clear cookies and restart the app it works for me

Still invalid response

**Comment by chanhh01** [comment]
> clear cookies and restart the app it works for me

Thanks it worked for me

**Comment by jasontran786** [comment]
I have the same issue, but when logged in only, back to normal when logout

**Comment by shreeyash17** [comment]
Same here
