### ISSUE TITLE
Invalid response 

### ISSUE THREAD

**Issue by shreeyash17** [Dar9586/NClientV2#482]
This issue is persisted through the week and i am not able to use the app at all plz check 

![Screenshot_2022-07-04-20-29-52-369_com dar nclientv2](https://user-images.githubusercontent.com/27241523/177179914-0cc1c762-ac44-4b7a-a0b2-b4282ad89e21.jpg

**Comment by kaisen7887** [comment]
Ye same here

I think last time the problem was dealt, there was browser poping up and the cloudflare was vertified everytime the "invalid response" showed up.

This patch it seems that the hidden browser never pops out even how many times the "invalid response" error was shown.

**Comment by sh1ntoo** [comment]
> Ye same here
> 
> I think last time the problem was dealt, there was browser poping up and the cloudflare was vertified everytime the "invalid response" showed up.
> 
> This patch it seems that the hidden browser never pops out even how many times the "invalid response" error was shown.

try to  clear cache

**Comment by kaisen7887** [comment]
> > Ye same here
> > I think last time the problem was dealt, there was browser poping up and the cloudflare was vertified everytime the "invalid response" showed up.
> > This patch it seems that the hidden browser never pops out even how many times the "invalid response" error was shown.
> 
> try to clear cache

Still doesn't work and the "hidden" browser still not poping up, i even add the force stop.Only way for me to bring that "hidden browser" back up is to do clear data.

Is there a way to possibly bring/force that "hidden browser" to the screen?

**Comment by ArniLord** [comment]
There's also a clear cookies button below clear cache. You could try that if you haven't already. Worked for me.
