### ISSUE TITLE
invalid respond

### ISSUE THREAD

**Issue by Weijuxian** [Dar9586/NClientV2#489]
1. Can't watch comics, the software can't load out comics, keep showing this picture
![Screenshot_2022-07-15-18-58-04-493_com dar nclien](https://user-images.githubusercontent.com/106127371/179211841-456b77d4-0876-4fa1-8a27-b1bf40276bdc.jpg)

**Comment by Weijuxian** [comment]
The problem has been solved

**Comment by 233tking** [comment]
how do you solve it?

**Comment by Nebelmischling** [comment]
Go to settings and clear Cache and cookies worked for me. But not permanently

**Comment by DuckEater54** [comment]
I tried that, it forced me to log in again and it gives the invalid response error again
