### ISSUE TITLE
Add language preferences

### ISSUE THREAD

**Issue by 0xh3LL0** [Dar9586/NClientV2#5]
is it possible to add language preferences?
for example, i just want english translated hentai appeared on my search, for now it can be done by adding "english" on the search.
but can we make it default?

**Comment by Dar9586** [comment]
if you click on the button with 3 line on top-left of the screen or swiping left you will open a menu and in the submenu Filters there is the selection for the language

**Comment by 0xh3LL0** [comment]
oops... sorry mate, i'm blind.
