### ISSUE TITLE
Bugs report 

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#51]
1.Created pdf are sorted out of order.
2.Save button in Single page viewer are invalid.

**Comment by ZerOri** [comment]
3.Function improvement:change app language according to system language.

**Comment by ZerOri** [comment]
4.Add feature:keep screen on when reading.

**Comment by Dar9586** [comment]
Could you specify better the problem with the 1

**Comment by ZerOri** [comment]
> Could you specify better the problem with the 1

Page order of the converted PDF files(change from downloaded manga)is disordered

**Comment by ZerOri** [comment]
5.Function improvement:Restore download items which in downloaded manga automatically.
