### ISSUE TITLE
In version 2.1.9.9 feature downlad screen not worked(save page in view page) and please add download lower quality into gallery.

### ISSUE THREAD

**Issue by deardian20** [Dar9586/NClientV2#52]
sorry for very much request

**Comment by deardian20** [comment]
![Screenshot_2019-12-04-16-34-33-52](https://user-images.githubusercontent.com/58062930/70131182-71f49480-16b4-11ea-9de1-ff77b5a13540.png)
And one more bug if many genre in doujin thumbnail will not load,just number.

**Comment by Dar9586** [comment]
The problem still persist? If yes, please provide some gallery example

**Comment by deardian20** [comment]
![Screenshot_2019-12-11-05-04-38-93](https://user-images.githubusercontent.com/58062930/70573130-e313da80-1bd3-11ea-927a-9f5036b36d26.png)
Still not loading

**Comment by hohommx2015** [comment]
Yes,i can confirm some galleries don't load thumbnails

**Comment by hohommx2015** [comment]
And the bug app stop loading any gallery after several uses seems came back

**Comment by hohommx2015** [comment]
@Dar9586 like this one: はぴねすみるく (おびゃー)_ 肉欲神仰信 - Episode of religious faith 3 - (東方Project) 
![超级截屏_20191213_085553](https://user-images.githubusercontent.com/23112624/70761041-73a40500-1d11-11ea-8886-5e7a0001fd55.png)

**Comment by hohommx2015** [comment]
I just his page number is
12
34
but mine is
21
43
Is this a bug？

**Comment by hohommx2015** [comment]
The thumbnail bug seems fixed in 2.0.2
