### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by EmsocOverlord** [Dar9586/NClientV2#53]
There are interestings features that would make using the app more pleasant:
![Screenshot_20191204-085953](https://user-images.githubusercontent.com/43179086/70141190-42726780-1675-11ea-81f4-b9d667f92b1a.png)
- Option to read the content as an "infinite scroll" because like in the image I got as an exemple some contents are better to read swapping vertically, this function could be listed next or in a menu with the save button
- A page "counter" with current page number/ total page number in the bottom part, it would be always visible so you don't have to touch the screen to see how much have you read

![Screenshot_20191204-090341](https://user-images.githubusercontent.com/43179086/70142118-48694800-1677-11ea-92c2-4cff6182f97f.png)

- In the loading pages you could add a "system" consisting of the logo of the app so the user know that the image is being loaded and an "X" To inform when the loading has failed so the user don't have to go back and re-open the image

**Comment by Dar9586** [comment]
All feature added in 2.0.5

**Comment by PhongTong** [comment]
Can you add share page/image function? Sometimes I just want to share a page, not a link. Thanks for your great work :)

**Comment by Dar9586** [comment]
Added in 2.0.6

**Comment by PhongTong** [comment]
Wow, that's fast. Thank you very much :+1:  

Btw, I notice the lack of history page when i try to find doujin from previous view . Can you add it in near future release?
