### ISSUE TITLE
Invalid response when opening app

### ISSUE THREAD

**Issue by overseer1301** [Dar9586/NClientV2#534]
When opening apk it tries to load and shows invalid response.the comics in favourites work fine but the main page is not loading. It sometimes flashes the login screen even though it is already logged in.I use the latest version of the app and use Android version 11.
 Image of problem attached 
![Screenshot_2023-02-06-09-00-20-15_4994b737716680d9ef83ff62fd52c895](https://user-images.githubusercontent.com/110413265/216877888-b69541af-a064-45b7-ac74-03c3677f3bf0.jpg)

**Comment by lamer15610** [comment]
see the solution in thread #529, installing an old version of the program helped many people
