### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by PING020903** [Dar9586/NClientV2#543]
can sign in, but no return books 
![Screenshot_2023-02-09-18-13-51-942_com dar nclientv2](https://user-images.githubusercontent.com/88314322/217783774-f6022ab2-4214-4e8a-9a08-f881724997b0.jpg)
![Screenshot_2023-02-09-18-13-47-683_com dar nclientv2](https://user-images.githubusercontent.com/88314322/217783773-d0deea85-31bb-4f21-8e5d-d0bf7b6e25d7.jpg)

**Comment by lamer15610** [comment]
see the solution in thread #529, installing an old version of the program helped many people
