### ISSUE TITLE
updated to 2.9.8 but still not work properly

### ISSUE THREAD

**Issue by RuiyiDeng** [Dar9586/NClientV2#545]
## Current Behavior

instead of invalid response, the new version just keep refreshing and don't came up with the thumbnails of the mangas.
![Screenshot_20230209_225226_NClientV2](https://user-images.githubusercontent.com/70970333/217996975-e9e8ca62-ab1c-4a66-83af-472be6a05e13.png)

**Comment by DatBoiOrly** [comment]
Yup can confirm that I'm getting the same issues it's not just you

**Comment by DatBoiOrly** [comment]
I've figured it out!! Basically when the popup screen for cloudflare pops up you wait for the verify your human to pop up and spam click it till it closes then it should boot as normal. If you click the hide button then you'll be stuck with this issue ;)

**Comment by RuiyiDeng** [comment]
alright just log out and log in again solved my problem :)
