### ISSUE TITLE
Checking website is secure,over and over again

### ISSUE THREAD

**Issue by saikamiku** [Dar9586/NClientV2#554]
App just stuck at checking web page...

**Comment by Akisamu** [comment]
I have the same problem which is never happened before. What's happened?

**Comment by Lycantant** [comment]
Same here 😔
![Screenshot_2023-02-13-13-32-38-916_com dar nclientv2](https://user-images.githubusercontent.com/16489337/218378662-7d63d18e-b881-4b43-9d3c-6d36f10c486a.jpg)

**Comment by Juanxc100115** [comment]
我也遇到了这个问题，网页可以进去，用app就会卡在这里

**Comment by saikamiku** [comment]
> 我也遇到了这个问题，网页可以进去，用app就会卡在这里

Same as me,i can.pass the secure check on browser but cant pass in this app,and i downloaded another nhentai android app which i can pass the security system,but i perfer this app,so plz debug this problem. Love ur app!

**Comment by EmiliaaKy** [comment]
Same issue

**Comment by moosje2003** [comment]
Use version 2.9.4
https://github.com/Dar9586/NClientV2/releases/download/2.9.4/NClientV2.2.9.4.Release.apk

**Comment by testing-playwright** [comment]
Fixed in latest release

**Comment by saikamiku** [comment]
> Fixed in latest release

Thanks bro
