### ISSUE TITLE
Chinese translation has not been updated

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#58]
Chinese translation has not been updated,which is a very important translation revision.

https://github.com/Dar9586/NClientV2/commit/8ac04aa6daf35fc7f6b38bdaac157be4a7da7145

https://github.com/Dar9586/NClientV2/commit/2e7f0757b1e211de0dd371c0cd42c3c24db31108

**Comment by Dar9586** [comment]
Fixed in 2.0.2
