### ISSUE TITLE
Feature request - Download as zip

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#59]
I believe some users manually archive downloaded folder as zip，it could be very handy if there's a download as zip option.

**Comment by Dar9586** [comment]
Added as option on 2.0.2 (long press on downloaded manga)

**Comment by hohommx2015** [comment]
First,thank you.But could it be an option that automatlly archive downloaded folders to zips？ That's what i requested,automatic operation is a game changer.

**Comment by hohommx2015** [comment]
Thank you
