### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Kadantte** [Dar9586/NClientV2#6]
~~Please don't close this issue I'll re-check the new version and post some Enhance here.~~

**Comment by Kadantte** [comment]
### **Enhancment:**

 1. Move Settings to the _**Main Menu**_
 
 ![enter image description here](https://i.imgur.com/RxjFm5Q.png)
 
 2. Main Menu, move the Settings here Also move _**Filters**_ to search bar.

![enter image description here](https://i.imgur.com/I4lh4c0.png)

 3. Filters, Add an " **+** " in search bar if click on it it will popup and show some Options like: [ Filters, Tags Filter ( if you can Add it like we set a tag that will never tha app search for it something like Yaoi or loli { This is just an Example }  ) .

![enter image description here](https://i.imgur.com/ApCzGlz.png)

 
 4. Clear Cache, Show cache size and message after press **Ok**.
 
 ![enter image description here](https://i.imgur.com/qFSnMVl.png)
 
 5. Update, Fix update option.

![enter image description here](https://i.imgur.com/jKxNEH6.png)

**Comment by Kadantte** [comment]
Todo list:

### **Progress:**

 - [ ] Move Settings to _**Main Menu**_.
 - [ ] Main Menu.
 - [ ] Filters + Search Bar.
 - [ ] Clear Cache.
 - [ ] Update.

**Comment by Dar9586** [comment]
Nice list. In the version 1.7.6 I included the points 1 and 4.
The error reported in point 5 is thrown by the library itself and cannot be removed. Here it is the docs:
![immagine](https://user-images.githubusercontent.com/11708347/52746808-b22e3d80-2fe2-11e9-95cb-98f7c9d7a7a7.png)
So the problem probably is of your connection. The only change I could do is tho show the error in the toast but it wouldn't be much useful

I want to integrate the points 2 and 3 creating a new Activity with all the options and maybe an history too, but it could require some time. If you have some tips for the new searchActivity I would be glad to hear them.

**Comment by Kadantte** [comment]
Okay, About the Updates it's from my End I'll see a Solution.
As you mentioned points 1 and 3 need some time there's no need for rush just take your time also I'll look a way to help you searchActivity.

**Comment by Dar9586** [comment]
Using the emulator I found out it was a problem of the certificates used in the older version of Android. I found a fix which can be used until API 16 (JELLY_BEAN) so it should work until this version.
I started creating the SearchActivity too

**Comment by Kadantte** [comment]
Sorry, I was working on something so I didn't login into my account.
If could do search features like this it will be nice:
As you can see here there is an " + " but if click on it, it turns into " x ":

 ![enter image description here](https://i.imgur.com/fcXKIxE.jpg)


and here after you Click on " + " as ytou can see there is Normal search you can put there popular tags :3 

 ![enter image description here](https://i.imgur.com/B1rp4HM.jpg)

Here after Enabling Advanced Mode:

 ![enter image description here](https://i.imgur.com/lT4j5Pm.jpg)

**Comment by Dar9586** [comment]
NHentai allows only to search using the queries and apply search by tags following the rules described in https://nhentai.net/info/ so it is not possible to use all that filters, the popular tags are the categories which are shown in the new search too.

**Comment by Kadantte** [comment]
I know that what i mean by popular tags is to put the most popular tags nhentai. you can find it at https://nhentai.net/tags/popular

**Comment by Dar9586** [comment]
I could put the first ten of each category always visible and selectable, the other tags instead like it is now, like this could go well?

**Comment by Kadantte** [comment]
Yea; This is better, Just trying to enhace this app to better way.

**Comment by tiagodamian** [comment]
Thank you guys for the app!
