### ISSUE TITLE
Bugs - Back button in RTL

### ISSUE THREAD

**Issue by py7hon** [Dar9586/NClientV2#60]
Back button reader not working in RTL
mode

![](https://a.gg.fm/WXAKw.jpg)

**Comment by Dar9586** [comment]
Only in reader it has problem?
I will try to fix it, but unfortunately these buttons are managed by the OS, so I could be unable to fix it

**Comment by Dar9586** [comment]
As I expected it is an OS problem, I couldn't replicate it and I wasn't able to fix
