### ISSUE TITLE
Can't download anything, when I press the download button it just displays it as continuosly buffering as opposed to an increasing percentage.

### ISSUE THREAD

**Issue by schmuque** [Dar9586/NClientV2#645]
![Screenshot_2023-08-12-09-55-23-589_com dar nclientv2-edit](https://github.com/Dar9586/NClientV2/assets/142085477/344dec5e-9bda-4039-a27d-0669093a056d)
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System version:

* NHentai link (if relevant):

**Comment by schmuque** [comment]
Pressing the play button doesn't do anything btw.

**Comment by shinparo** [comment]
Try force stopping the app that usually fixes it whenever I encounter this problem.

**Comment by schmuque** [comment]
> Try force stopping the app that usually fixes it whenever I encounter this problem.

Thanks, this fixed it.

**Comment by schmuque** [comment]
Force stop the app

**Comment by Dethrath** [comment]
It doesn't work
