### ISSUE TITLE
Unable to connect to site

### ISSUE THREAD

**Issue by NotYeMK** [Dar9586/NClientV2#673]
Expected Behavior
- opening galleries

Current Behavior
- Not opening galleries and showing "unable to connect to site" 

Possible Solution
- likely API issues

Steps to Reproduce (for bugs)
- open app
- tap gallery
- warning pops up
Context

Your Environment
Version used: the most current stable release
Operating System version: Nothing OS 2.0.3

**Comment by TheOneEyedGrimReaper** [comment]
I have the same problem too.
