### ISSUE TITLE
Error: Unable to connect to the site

### ISSUE THREAD

**Issue by PhantomNimbi** [Dar9586/NClientV2#675]
The app won't open anything that I tap. It loads the previews, but when I tap to open anything it just shows `Error: Unable to connect to the site`

* **OS**: Android 13
* **Device**: Samsung Galaxy S20+ 5G
* **App Version**: v3.0.2-stable-release

* **Screenshot(s)**:
![Screenshot_20231116_143010_NClientV2.png](https://github.com/Dar9586/NClientV2/assets/17615050/4cfce822-d1d3-4f39-8231-0b2893251d77)

**Comment by AfrizalFirmansyah** [comment]
Same here Error: Unable to connect to the website
Android 12
Passed cloudflare
List of doujin loaded, but when click on selected error unable to connect.

**Comment by 3172789077** [comment]
有解决办法没

**Comment by BandaiGK** [comment]
Sameee, any time I try to open the things it won't open and say **Unable to connect to the website**, I also passed the cloudflare without trouble😵‍💫

**Comment by 3172789077** [comment]
> Sameee，任何时候我想打开的东西它都不会打开说**无法连接到网站**，我也顺利通过了云耀--‍💫

有具体解决办法没有

**Comment by BandaiGK** [comment]
> > Sameee，任何时候我想打开的东西它都不会打开说**无法连接到网站**，我也顺利通过了云耀--‍💫
> 
> 有具体解决办法没有

Haven't seen one, only thing I can do is hope some day it gets fixed 😂

**Comment by 3172789077** [comment]
先生，有些色色

**Comment by ChiefOfLoliPolice** [comment]
Yup going through the same thing. I can read any manga I add to the status viewer regardless of folder but any manga that loads up on the main screen says "unable to connect to site".

**Comment by 3172789077** [comment]
没法解决

**Comment by peroroo** [comment]
> Can't wait for fix? Then submit a pr
Lol

**Comment by BandaiGK** [comment]
There's already been a lot of new updates and doujins and I can't see them 😂😔

**Comment by PhantomNimbi** [comment]
> > Can't wait for fix? Then fix it by yourself and submit a pr
> 
> 
> Lol

Would if I knew how, lol. I'm not skilled in android app development, sadly. So I'm content with waiting for a fix.
