### ISSUE TITLE
When I try to open a manga it gives error: unable to connect to site. But the site is up and I can access it via browser

### ISSUE THREAD

**Issue by KubikulaPOG** [Dar9586/NClientV2#685]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System version:

* NHentai link (if relevant):

**Comment by Thesupafly** [comment]
I also have this problem has anyone found a fix yet I had this error since yesterday
