### ISSUE TITLE
[FIX] Unable to connect to site bug

### ISSUE THREAD

**Issue by LazyLinker** [Dar9586/NClientV2#687]
Apparently admins changed order of <script> tags in template. Instead of last on page it is now second. So here is my lazy fix.

app\src\main\java\com\dar\nclientv2\api\InspectorV3.java

row 377 change
String json = trimScriptTag(scripts.**last()**.html());
to this line
String json = trimScriptTag(scripts.**get(1)**.html());

Probably better to come up with some sophisticated checks instead of indexation.

here u go >>
![Screenshot 2023-11-19 053105](https://github.com/Dar9586/NClientV2/assets/85456372/934a6e92-1724-4934-90d2-e90982a085ae)

**Comment by LazyLinker** [comment]
If someone is too lazy to build here's debug version. Will not override release in case someone treasures their collections
[app-debug.zip](https://github.com/Dar9586/NClientV2/files/13402100/app-debug.zip)

**Comment by 3172789077** [comment]
大哥真牛逼

**Comment by LTSUM** [comment]
how can I fix it on phone?

**Comment by xiaojie2222** [comment]
I can't find the file path.

**Comment by xiaojie2222** [comment]
> 大哥真牛逼

大哥发的这个文件路径找不到啊

**Comment by Crackenzxnd** [comment]
> If someone is too lazy to build here's debug version. Will not override release in case someone treasures their collections [app-debug.zip](https://github.com/Dar9586/NClientV2/files/13402100/app-debug.zip)

In this version, I can't download the manga

**Comment by LazyLinker** [comment]
> how can I fix it on phone?

> I can't find the file path.

unfortunately it's impossible to fix it directly on device. There are 2 options: 

1. dowload repository on pc, make proposed change and buid an apk
2. wait for owner of this repository to accept pull request

**Comment by LazyLinker** [comment]
> > If someone is too lazy to build here's debug version. Will not override release in case someone treasures their collections [app-debug.zip](https://github.com/Dar9586/NClientV2/files/13402100/app-debug.zip)
> 
> In this version, I can't download the manga

Same here. Was not able to dowload for months.
From what I understand Android 12.+ changed the way external_storage_permision works. In code methods that check/enable this permission always return false. I tinkered a bit with code but I had 0 success. Basicly this function needs an update from someone who understand a thing or two about this platform
