### ISSUE TITLE
Crashes associated with Login and no way to reset on root disabled device

### ISSUE THREAD

**Issue by Lilica1** [Dar9586/NClientV2#7]
Instant Crashes on launch client. 
Unknown Issue

**Environment**

Android 8.0
Phone with no root

**Reproduction** 

1. Launch Client
2. Login to NH account
3. (by random) Home page will not load
4. Quick Switching between menus till it crashes
<Before leading to the ultimate chain of crashes, it will only be caused when launching client with a empty home screen and trying to log out, logging out will crash the client>
5. (by random) App will start to instant quit while trying to launch <Chain of death>

**Attempted**
1. Reinstall current version
2. Reinstall a previous version
3. Reinstall debug release current and previous version
4. Clean all associated folders except root folder and attempted 1,2,3

**Comment by Lilica1** [comment]
Current version refers to NClientV2 1.7.8

**Comment by Dar9586** [comment]
It should be fixed in 1.7.9

**Comment by Lilica1** [comment]
Confirmed fix, thank you for the hard work
