### ISSUE TITLE
Add feature - delete picture in galery

### ISSUE THREAD

**Issue by deardian20** [Dar9586/NClientV2#70]
Because if i download galery and have crash picture, download will not loaded.

**Comment by Dar9586** [comment]
I'm not sure to understand the problem, could you be more detailed and maybe provide some screen

**Comment by deardian20** [comment]
If i have crash picture when download gallery,the picture can't redownload
into a original picture it must be delete from file manager and then worked.

Sorry my english language is bad.

Pada tanggal Min, 29 Des 2019 18.15, Dar9586 <notifications@github.com>
menulis:
