### ISSUE TITLE
External link problem

### ISSUE THREAD

**Issue by eme22** [Dar9586/NClientV2#71]
When an external link is opened in the app it goes directly to read mode instead of going to the manga Main screen as it does before, the problem here is that i cannot add to favorites the mangas from external links. The problem here is that the manga cannot be added to favorites
[Video](https://drive.google.com/file/d/10X-SdPWa8frnQ3kHkdT-KuY8OEy7jDDh/view?usp=drivesdk)

**Comment by Dar9586** [comment]
Fixed in 2.0.5, now even if you open a specific page the gallery screen remain active
