### ISSUE TITLE
Unable to connect to the site. 

### ISSUE THREAD

**Issue by fauzisidith** [Dar9586/NClientV2#746]
I'm using nclientv2 version 3.0.5.
When I click the thumbnail, a message popup shows "Unable to connect to the site" at the bottom.

I have tried using the debug version. 
![Screenshot_20241102_162852_com dar nclientv2](https://github.com/user-attachments/assets/587307bb-4297-4c50-a228-4dc4cbc3286e)

But, same problem persist.

**Comment by Abc6767** [comment]
Same

**Comment by GODxEnvy** [comment]
in other comment i found solution. 
export ur data then delete the app. the download 3.0.2 version. and you can import data.

3.0.5 and even 3.0.4 version have problem. but 3.0.2 version seems to work just fine.

**Comment by lamer15610** [comment]
https://github.com/Dar9586/NClientV2/issues/744#issuecomment-2452810317
