### ISSUE TITLE
Crashing when opening local favorite tab

### ISSUE THREAD

**Issue by RCaled** [Dar9586/NClientV2#76]
The app keeps crashing when the favorite tab is selected. 
I think the reason for this error is that some time ago I favorited a gallery that is now deleted and I cannot remove the favorite. I tried searching the code of the gallery through a browser and entering directly to it from the search bar then the app crash again. 
The code of the gallery causing this problem is 288395. 
I need at least a way to save or export my local favorites.

**Comment by Dar9586** [comment]
Should be fixed in 2.0.7, otherwise install the debug version and enable send crash report

**Comment by RCaled** [comment]
The bug of the favorite tab is still in 2.0.8. I can access to the deleted gallery since 2.0.7 but there is no option to remove the favorite. Send crash report is enabled where is it stored?

**Comment by RCaled** [comment]
Thank you. Issue is solved in 2.0.9.
