### ISSUE TITLE
Project Abandoned - New fork -  Searching for developpers

### ISSUE THREAD

**Issue by maxwai** [Dar9586/NClientV2#764]
Is @Dar9586 still maintaining this app? 

The Last commit on Main was from a year ago and there isn't any response on Issues or Pull Requests.

If this is so, maybe opening a main Fork of the App would be best so that the app can be maintained further.

**Comment by sander1946** [comment]
By the looks of it, @Dar9586 has abandoned this project. I don't know why or under what circumstances. I think that it's for the best if there were some people that could fork the repo and continue the work on it (maybe under a different name). But I don't know much about app making on android, and thus will not do it myself.

But do keep me updated if someone did fork it and continue to maintain it

**Comment by sander1946** [comment]
But if your app is crashing, you can get a debug version that someone made in the pull request #762

**Comment by maxwai** [comment]
There is a fork with multiple Stars the appears to be continuing development https://github.com/shirokun20/NClientV2

But @shirokun20 should say if he is willing to have his repo be the official fork or someone else should do it.

**Comment by shirokun20** [comment]
No bro, just for learning the code and convert to other mobile language like flutter and react native 

> There is a fork with multiple Stars the appears to be continuing development https://github.com/shirokun20/NClientV2
> 
> But @shirokun20 should say if he is willing to have his repo be the official fork or someone else should do it.

**Comment by maxwai** [comment]
Ok, since there still wasn't any sign of life from @Dar9586 I will consider this project as abandoned by him.

As shirokun20 didn't wan't his fork to be the official new version I would start planning a new Fork.
I would make this fork as part of a organisation so that this problem doesn't happen again as multiple people will have write access to the repo.

On that note, we would need some willing developers/maintainers that can work on this app. I can work a little bit on this app but since I'm still a master student I don't have a lot of free time that I can put into this project. I would however be willing to handle organizing the fork and manage the releases.

With that said, please write a comment on this issue if you are interested on working on this project.

**Comment by shirokun20** [comment]
Thanks sir

**Comment by Stefan-Lindenmeyer** [comment]
Hey @maxwai,
I am currently in need of a coding project in my spare time and I'd like to offer help if it is accepted.
I have to warn you though. 
I am very rusty in Java, have basically never done app development before and would have to work through the existing code first when I have time and then learn about how I can add to it or fix things. So I should probably not be a lead dev, or anything like that, to start (if even possible).

**Comment by maxwai** [comment]
As the interest was low with only one person proposing to help, I will create a fork but as a personal repo and not as organisation repo.

The fork can be found here: https://github.com/maxwai/NClientV2-ng

It will take me 1-2 weeks to get everything up and running and start fixing things, but I will start with the most pressing issues, mainly the new image format and image loading.
