### ISSUE TITLE
[Feature Request] Download resume

### ISSUE THREAD

**Issue by linsui** [Dar9586/NClientV2#84]
When downloading a gallery, if a network error occurs,  the download will be regarded as completed. Then I have to delete the gallery and redownload it. I hope there is an option to resume the download. Thanks!

Edit: I found that I can resume gallery downloading but if an image is broen I can't redownload it.

**Comment by Dar9586** [comment]
Now should work properly

**Comment by linsui** [comment]
Thanks! Now a gallery can be downloaded completely but there are lots of broken images.

![IMG_20200404_183602](https://user-images.githubusercontent.com/36977733/78424928-64bbd680-76a3-11ea-896a-9df184c280a1.jpg)
