### ISSUE TITLE
Add different reading directions

### ISSUE THREAD

**Issue by neslxzhen** [Dar9586/NClientV2#85]
Hope to add top-down browsing

加入不同的閱讀方向
希望能加入由上至下的瀏覽方式

**Comment by Dar9586** [comment]
Top-Down browsing can be achieved using the column switcher for the gallery viewer
![Screen](https://user-images.githubusercontent.com/11708347/78422562-6ca65700-7660-11ea-92b3-142572e73267.png)

**Comment by neslxzhen** [comment]
i know, but that can't drag to enlarge likely default reading direction.

我知道，但是他不能像預設那樣透過雙指拖動來放大圖片

目前的解決方式只是一種閹割版，很多進階的功能都被閹割了

**Comment by Dar9586** [comment]
I could, when the gallery is in 1 column mode, enable the image to be enlarged
