### ISSUE TITLE
Feature - random for favorites

### ISSUE THREAD

**Issue by FrozenTear7** [Dar9586/NClientV2#86]
One feature that would be very useful is a **random button** for favorites section as exists on the official website:
![RandomFavorites](https://user-images.githubusercontent.com/31183971/77849044-0be2ce80-71c9-11ea-9f58-83eb1cf39bb3.png)

My suggestion would be to add filters to the already existing view **Random manga** - it would also allow to expand this feature in the future to search randomly with given tags.

**Comment by Dar9586** [comment]
Added in 2.1.2
