### ISSUE TITLE
App not working on my Android as previously builds worked

### ISSUE THREAD

**Issue by eme22** [Dar9586/NClientV2#88]
Since This build. The app completely won't open. 
[https://del.dog/ninudexori](https://del.dog/ninudexori) 
![Screenshot_20200408-173756](https://user-images.githubusercontent.com/48258734/78840298-fd15cc00-79bf-11ea-95a9-234b149cfbd3.jpg)

**Comment by myxiuren101** [comment]
Same issue, but works after reinstall

**Comment by eme22** [comment]
Yep but local favorites will be gone if I reinstall

**Comment by eme22** [comment]
That's it. Keep the good work Dar9586, Greetings.
