### ISSUE TITLE
Cant enter a tag

### ISSUE THREAD

**Issue by biscoitenho** [Dar9586/NClientV2#90]
When in a title, i cant enter in a TAG on It

**Comment by myxiuren101** [comment]
If you mean clicking on a tag when in a gallery does not show results, then I have the same issue. Some tags work, some tags don't

**Comment by Dar9586** [comment]
Could you provide some example (the id of the gallery and the tag)

**Comment by Dar9586** [comment]
Fixed in 2.1.4
