### ISSUE TITLE
Detail page title is not fully displayed.

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#92]
No matter the horizontal or vertical screen, the title is not fully displayed, I hope to solve it.

![TIM图片20200415103402](https://user-images.githubusercontent.com/46775615/79293124-6be5ae80-7f05-11ea-982d-89e16c033e7e.jpg)

![TIM图片20200415103408](https://user-images.githubusercontent.com/46775615/79293127-6e480880-7f05-11ea-9ae7-e256c0fe864f.jpg)

**Comment by Dar9586** [comment]
Added a collapsable title when opening the gallery
