### ISSUE TITLE
Search result is blank when there are more than 1 filter label.

### ISSUE THREAD

**Issue by ZerOri** [Dar9586/NClientV2#93]
### Is this a bug?

![TIM图片20200415110344](https://user-images.githubusercontent.com/46775615/79297946-398e7e00-7f12-11ea-9841-a716c81e46bf.jpg)
![TIM图片20200415110350](https://user-images.githubusercontent.com/46775615/79297952-3b584180-7f12-11ea-95d8-9edbf901b119.jpg)

**Comment by Dar9586** [comment]
This isn't a bug, simply there isn't any manga created by both saigado and sasamori tomoe, if you search on NHentai it will also say that there aren't results
